src/namespaces.json
src/views/Proposals.vue

- Add community proposals tab 
- Add Core Dev proposals tab
- Add `coreDevs` to namespace

Add Community and Core Devs Tabs

---

src/namespaces.json

add invalid proposals for YAM

---

package-lock.json
package.json
src/views/Create.vue
src/views/Home.vue

- Allow choices to be reordered by dragging
- Transitions for choice additions/deletions and reorder

make choices draggable with transition

---

spaces/lao/index.json

update LAO Community ticker to `LAO-C` for clarity (tiny change)

Update LAO index.json (ticker change)

---

spaces/sushi/index.json

Remove duplicates for SIP-6 SWRV-ETH

---

spaces/aave/skin.scss

- Add Aave gradient to bottom border at topnav

Added Aave gradient at bottom border of topnav

---

src/store/modules/web3.ts

As suggested here https://github.com/bonustrack/snapshot-spaces/pull/27#discussion_r488413425
- Add mybit to noDecimals as it doesn't have decimals() method

Add mybit to 'noDecimals'

---

.env
src/components/Topnav.vue
src/config.json
src/helpers/rpc.ts
src/helpers/ws.ts
src/store/modules/web3.ts
src/views/Home.vue

Add chainId config var

---

src/helpers/networks.json

Fixes # .
- Add Wanchain Network Config - Removed Trailing Slash From URL
- 
-

Add Wanchain Network Config - Removed Trailing Slash From URL

---

src/components/Plugin/Gnosis/Block.vue
src/components/Plugin/Gnosis/Config.vue

- Add the choices name on preview when a new Gnosis Impact is added.
- Add check number of the choices on the block view.

Add choices to add preview Gnosis plugin

---

src/components/Block/Votes.vue

Fixes #179 
- rearrange votes before they are sliced in visibleVotes()
- 
-

feat: issue#179 show user vote at the top

---

vue.config.js

Fixes #101 
https://ipfs.io/ipfs/QmPuQoAH56WQizLD1kQ7SzgNNUEUvJ6cxQRfM8Ti1MTC6q/#/
without extension or relative path works now

Relative path for IPFS deployments

---

src/components/TextareaArray.vue

Fixes #199
- Use watcher instead of event listener to trigger handleInput
- 
-

fix: #199 Data now updates properly

---

package-lock.json
src/shims-vue.d.ts
src/store/modules/web3.ts

Fixes # . https://github.com/balancer-labs/snapshot/issues?q=is%3Aissue+is%3Aclosed
- Torus connector merge fix seems to be missed merged. Not working on prod, added back the auth.value.isTorus check before removing liseners similar to https://github.com/balancer-labs/snapshot/pull/184/files
We've added this to a sprint to fix in the long-term so it doesnt create further issues here, but this is a quick fix for now @bonustrack

fixed reference by adding auth.value

---

src/components/Layout.vue
src/views/Create.vue
src/views/Delegate.vue
src/views/Proposal.vue
src/views/Settings.vue
src/views/Setup.vue
src/views/Strategy.vue
src/views/Timeline.vue

Fixes #216 
- Move content/sidebar layout classes to a layout component 
- 
-

feat: Layout component

---

src/helpers/profile.ts

Fixes # 
https://snapshot.page/#/yam.eth/proposal/QmSjqiubKe5UZ5aWV7oZGq1z1utE4tE3nPyeyJgXQAgjRX
Previous: 
Current:

ENS Names consistency

---

src/components/Ui/Calendar.vue

fix: Timezome bug when formatting the date

---

src/components/Plugin/Gnosis/CustomBlock.vue

Fixes `proposalConfig.network` values for old proposals.

Fix default `proposalConfig.network` Gnosis plugin

---

src/helpers/profile.ts

https://snapshot.page/#/snxambassador.eth/proposal/QmXmaLWvWmr3p6wX9Yg5nQ4XqtZmcxCkbFUMtWJKg74SLh

ENS Names consider Label Name also

---

LICENSE
package.json

Balancer to snapshot typo fix

---

src/components/User.vue
src/style.scss

https://snapshot.org/#/graphprotocol.eth/proposal/QmNTUFcx5SGt3Jd1heDmKa6Lh8WGmJnqKiii7H91RUAbKW
Before: 
After:

ENS Names Overflowing issue

---

package-lock.json
src/components/Modal/Plugins.vue
src/components/Plugin/DaoModule/Config.vue
src/components/Plugin/DaoModule/CustomBlock.vue
src/components/Plugin/DaoModule/TransactionPreview.vue
src/views/Create.vue
src/views/Proposal.vue

This adds support for the [DAO module](https://github.com/gnosis/dao-module) to snaphot. 
This depends on https://github.com/snapshot-labs/snapshot.js/pull/108
TODOs:

DAO module support

---

src/App.vue
src/components/Modal/About.vue
src/components/Modal/SelectLanguage.vue
src/components/Topnav.vue
src/helpers/utils.ts
src/i18n.ts
src/locales/default.json
src/locales/languages.json
src/mixins.ts
src/store/modules/app.ts

feat: Language switcher modal

---

src/components/Modal/Strategies.vue

Fixes #274 
- Shorten and link if value is address

fix: Shorten and link if value is address

---

src/locales/languages.json

Update languages.json (add PT + ID)

---

src/locales/languages.json

Update languages.json (add SV-SE)

---

src/views/Proposal.vue

- Also changed the name of the loading state, in preparation for more items

Allow admins to delete/archive proposals

---

src/components/Modal/Receipt.vue

Fix mycrypto verify message link

---

src/views/Timeline.vue

Fix timeline pagination

---

src/views/Create.vue

This is a quick fix and I will make another PR later today with more optimised queries.

Fix create proposal from

---

src/composables/useElementWatcher.ts
src/composables/useScrollMonitor.ts
src/helpers/utils.ts
src/views/Explore.vue
src/views/Home.vue
src/views/Timeline.vue

Fix scroll listeners

---

src/components/Modal/User.vue
src/components/User.vue
src/mixins.ts

Fixes avatar image URL 
https://snapshot.org/#/cafeswapfinance.eth/proposal/QmRJhiUmEdtTXQRxVAiCEmBye1RJBPfBbqr9JSaKroJ8FM
also fixes an error when user model is opened - getting ipfs null error

Fix user profile ipfs url

---

src/components/Plugin/Quorum/CustomBlock.vue

This PR converts the quorum property to a computed property, thus recomputing it dynamically and re-renders whenever a vote has been casted

Quorum Plugin: Convert the quorum property to a computed property

---

src/locales/languages.json

Update languages.json (add TR)

---

src/components/Plugin/SafeSnap/CustomBlock.vue
src/locales/default.json

Fixes: Now users can claim bond from the Snapshot dApp, instead of having to go to realitio dApp.
- Add claim bond button to SafeSnap Custom block
-

Feat: Claim bond functionality implemented

---

src/components/Voting/Quadratic.vue

Fixes https://discord.com/channels/707079246388133940/747049240022482974/855613275394670644

Fix input not updating on quadratic voting

---

package.json
src/components/Plugin/SafeSnap/CustomBlock.vue
src/helpers/abi/utils.ts

This PR executes a batch of transactions using the Multi-Send Contract.

SafeSnap - Execute Transactions Batch with Multi-Send Contract

---

src/components/Plugin/SafeSnap/Form/SendAsset.vue
src/components/Ui/Popover.vue
src/components/Voting/Quadratic.vue
src/helpers/snapshot.ts
src/helpers/utils.ts

because of new changes in snapshot.js

Removed unwanted code - which is throwing error

---

src/store/modules/web3.ts

Steps to reproduce:
1. Change network in Metamask from current network to any network
2. Change account in Metamask
3. See bugged out wallet button in UI and error in console

Fix wallet bug when changing account

---

src/locales/languages.json

Update languages.json (add VN)

---

src/locales/languages.json

Update languages.json (add MR)

---

src/components/Plugin/POAP/CustomBlock.vue
src/locales/default.json

Fixes # .
- Changed text `Show me my badges` to `Show me my collection`
- Changed image URL

POAP plugin style fix

---

src/views/Playground.vue

Network auto populate on playground

---

tsconfig.json

Revert to esnext

---

src/helpers/abi/utils.ts

SafeSnap - Fixes

---

src/locales/languages.json

Update languages.json (add KR)

---

src/locales/languages.json

Update languages.json (add DK)

---

src/router.ts
src/views/Delegate.vue

Delegate address autopopulate

---

src/locales/languages.json

Update languages.json (add CZ)

---

src/views/Delegate.vue

Fix delegate page not showing actions

---

package.json
patches/idna-uts46-hx+2.3.1.patch
src/helpers/profile.ts
yarn.lock

Fix ENS reverse record with patch

---

src/locales/languages.json

Update languages.json (add IL)

---

package.json

New changes from github (snapshot-spaces) doesn't reflect

Fix spaces not checking latest commit

---

.github/workflows/manual.yml

we can trigger a workflow from GitHub actions, so we don't have to deploy from Fleek when spaces are changed
will add a new commit like below:
Example repo: 
https://github.com/ChaituVR/snapshot

Manually update submodule github

---

src/views/Proposal.vue

Fix proposal redirection

---

src/views/Home.vue

Fixes #621
- Use flex-wrap approach instead of margin-right with float left.

style(): fix grid so that the gaps are not clickable

---

src/views/Home.vue

fix(): full width no results component

---

src/components/MainSidebar.vue

fix(): use router-link (a tags) for better accessibility

---

src/components/Ui/Avatar.vue

fix(): avatar getting squished

---

src/App.vue
src/components/TheSidebar.vue
src/components/Ui/Avatar.vue
src/components/Ui/Counter.vue
src/components/Ui/Markdown.vue
src/composables/useUserSkin.ts
src/style.scss
src/views/Home.vue

Fixes #647 
- implemented a hook to get the current userSkin

feat(): added a theme switcher

---

src/components/Modal/Skins.vue
src/style.scss

- the default skin will show the correct skin depending on the userSkin (dark / light)
- Selecting will remove the custom skin set for the space.
Fixes #652.

feat(): add default skin option

---

src/components/Voting/RankedChoice.vue

Fixes #653 
I managed to add a flex behaviour to the elements inside the Button, removing the needing for absolute positioning.

#653 Space elements on voting with space between instead of absolute

---

yarn.lock

Fix join space

---

src/components/Block/Space.vue

feat(): added members count to the proposals page

---

src/helpers/utils.ts

Terms null fix

---

src/components/Ui/Input.vue
src/style.scss

Fixes # .
- Fixed input error statement
- Also fixed focus statement on input

fix: error and focus border-color

---

src/composables/useFollowSpace.ts
src/views/Home.vue

Fixes # .
- Changed route query param `q` at line 15 to `network`
- Also I've rename this variable to `network` for more consistency =)

fix: network filter

---

src/components/Notifications.vue

Fixes # .
- Fix styles using `!` prefix on border and background styles
- 
-

fix: forcing border & bg styles

---

src/helpers/queries.ts

Fixes https://github.com/snapshot-labs/snapshot/issues/801

Fix settings not persisting on Ui after save

---

src/views/Delegate.vue

Fixed https://github.com/snapshot-labs/snapshot/issues/798

Fix delegation error when typing a ENS

---

src/components/Plugin/CommentBox/Comment.vue
src/components/Plugin/CommentBox/CommentBlock.vue
src/components/Plugin/CommentBox/CustomBlock.vue
src/components/Plugin/CommentBox/ListReply.vue
src/components/Plugin/CommentBox/ReplyBlock.vue
src/components/Ui/Tooltip.vue

remove unnecessary imports

---

src/components/Modal/Confirm.vue
src/composables/useClient.ts

Reverts snapshot-labs/snapshot#800

Revert "Send "vote-safe" type when using Gnosis safe and show some other noti…"

---

src/main.ts

removed duplicate plugin use

---

package.json
src/components/Plugin/SafeSnap/Config.vue
src/views/Playground.vue

https://stackoverflow.com/a/67273107/5916893

Lint doesn't work (could be happening only in few opereating systems)

---

src/components/Ui/Input.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/886

Remove scroll bar on inputs with selected

---

src/style.scss
src/views/SpaceSettings.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/884

Try to fix select color on windows

---

src/App.vue

Fixes... nothing but I'd feel better. :P

remove duplicate html id

---

src/App.vue

This reverts commit 16a53e09ae8d2533ee28ab23535267328be26ae0.
Fixes https://discord.com/channels/707079246388133940/817492434636111977/898824834291748865

Revert "remove duplicate html id (#894)"

---

src/components/Scroller.vue
src/style.scss
tailwind.config.js

Fixes https://github.com/snapshot-labs/snapshot/issues/892

Add no-scrollbar class for all browsers and remove scroller sidebar firefox

---

src/components/Ui/Calendar.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/840

Remove arrow for prev months and make prev days not selectable

---

src/views/SpaceCreate.vue

Fixes #982 
Changes:
- Remove choice cleanup after changing type from "Basic"

Fix cannot add choice by removing the choice cleanup

---

src/components/Block/Votes.vue
src/helpers/snapshot.ts

See more paginated

---

src/helpers/queries.ts
src/helpers/snapshot.ts
src/views/SpaceProposal.vue

fix(): split votes and proposal

---

src/helpers/profile.ts

removed unused function

---

src/components/Block/Votes.vue
src/components/Modal/Confirm.vue
src/components/Modal/Strategies.vue
src/components/User.vue
src/helpers/snapshot.ts
src/views/Playground.vue
src/views/SpaceProposal.vue

Use proposal network instead of space network

---

src/components/Ui/Markdown.vue

Fixes # .
- add option to remarkble

fix: proposal links

---

src/helpers/queries.ts

Fixed proposal validation on space settings

fix(): validation for space settings

---

src/composables/useWeb3.ts
yarn.lock

fix(): gnosis connector

---

src/components/User.vue

truncate long user names

---

patches/@snapshot-labs+lock+0.1.3.patch

Fix gnosis safe wallet issue

---

src/views/Timeline.vue

Fix timeline borders

---

src/components/Ui/Calendar.vue
src/composables/useI18n.ts

Fixes https://github.com/snapshot-labs/snapshot/issues/1158
-  use latest locale 
English
Chinese 
@bonustrack @ChaituVR

fix calendar locale issue

---

src/composables/useInfiniteLoader.ts
src/composables/useState.ts
src/composables/useStore.ts
src/views/SpaceProposals.vue
src/views/Timeline.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1138
- Create and new State composable for storing proposals persistently
- Rename `following` computed property for readability
- Fix spaces no longer reloaded when changing route to none filters

Add persistence to proposals state

---

src/components/FollowButton.vue
src/views/Home.vue

Fix height and ability to right/mouse click

---

src/components/Search.vue

Fixes # .
- search add debounce

add search debounce

---

src/components/Ui/Markdown.vue

Fixes #1192  
- Markdown.vue scss, reduced font size
@bonustrack

decreased font size for .markdown-body code, fix #1192

---

src/views/SpaceProposal.vue

Fixes #1141 
- Go back to previous page if browser tab has history to go back to
- If there is no history go back to space
- Show the appropriate button text depending on the case

Fix proposal back button behavior

---

src/components/Modal/Receipt.vue

As a part of https://github.com/snapshot-labs/snapshot/issues/853

chore: use space instead of margin for spacing

---

src/components/Block/Space.vue
src/locales/default.json

Feature #1176 .
- add verified space

reslove #1176: add verified space

---

src/views/SpaceCreate.vue

feat: add cursor-pointer to remove choice input for better a11y

---

src/views/SpaceProposals.vue

Fix proposals being loaded twice 

---

README.md

This help us show the activity of the project and more visibilities on bounties

feat: add commit activity and help wanted badges

---

src/views/SpaceCreate.vue
src/views/SpaceProposal.vue

Fixes #1270 
1. Cleared proposal value to []

Cleared proposals after create and delete

---

src/views/SpaceProposals.vue

Fixes #1288 
- Move check into watchEffect

Fix showing wrong proposals when changing space while loading

---

src/views/Timeline.vue

Fixes #1343 .
- fixed: timeline not logged loading

fixed: timeline not logged loading #1343

---

src/views/SpaceProposals.vue

Fixes #1394 
- Fixes infinite requests on space proposals when there are no proposals

fix: infinite loading of proposals when space don't have any proposal

---

.github/dependabot.yml

Reverts snapshot-labs/snapshot#1414

Revert "Dependabot updates for @snapshot-labs/snapshot.js separately"

---

src/composables/useWeb3.ts

Fixes https://discord.com/channels/707079246388133940/747049240022482974/929729296229089320

Fix isTrezor is always false because of conditional bug

---

src/App.vue
src/style.scss

Fixes https://discord.com/channels/707079246388133940/747049240022482974/930763623264051201

Fix min-height bug and other potential bugs

---

src/components/Topnav.vue

Fixes # .
- Removed setTitle in the Topnav component
- It's function is now handled by setPageTitle

Removed setTitle in the Topnav component

---

package.json
yarn.lock

Update snapshot.js version

---

src/views/SpaceProposal.vue

Fixes https://discord.com/channels/707079246388133940/831512954435534898/933700451029885009
- Remove space name from back button so we can lazy load the space

Fix proposal loading and space name undefined

---

src/views/SpaceProposals.vue

show NoProposals component only once space is loaded

---

src/locales/default.json

Fixing text to say "Tell us more about your proposal (optional)" vs "Tell more about your proposal (optional)"
Fixes # .
- Fixing the text so it sounds right.

Fixing text.

---

src/components/Block/Network.vue
src/components/Block/Plugin.vue
src/components/RegisterENS.vue
src/locales/default.json
src/views/Setup.vue

- Fix network and plugin block alignments
- Move text and html into defaults.json
- Fix setup input alignments

Fix UI alignments and refactor

---

src/components/SearchWithFilters.vue
src/components/Ui/Dropdown.vue
src/views/Explore.vue
src/views/SpaceProposals.vue
src/views/Timeline.vue

- Show selected item in search, timeline and spaceProposals dropdown
- Fix watcher warnings
- Fix dropdown key warning 
- Fix not updating seen proposals on first load
- Fix clickable area on search filters

Fix general bugs

---

src/components/Voting/RankedChoice.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1541

Fix alignment on RCV selected choices

---

src/components/Block/Votes.vue

Fix alignment of choice string in votes block

---

components.d.ts
package.json
src/components/Ui/Avatar.vue
src/components/Ui/State.vue
src/style.scss
tailwind.config.js
vite.config.ts
yarn.lock

Everything works as expected, no ui breaks 😄
As a part of #1452
Inherited from https://github.com/snapshot-labs/snapshot/pull/1251

chore: upgrade tailwindcss to v3

---

components.d.ts
src/components/Plugin/CommentBox/Comment.vue
src/components/Plugin/CommentBox/CommentBlock.vue
src/components/Plugin/CommentBox/CustomBlock.vue
src/components/Plugin/CommentBox/ReplyBlock.vue

Fixes #1550
https://user-images.githubusercontent.com/69431456/151702815-6c0d394b-5b98-422c-badb-ba1de398696c.mov

fix: wrong token when switching accounts in comment box

---

src/views/SpaceSettings.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1576#issuecomment-1026836280
- Prefill admins field with owner address if not already present

Fix settings in sidebar doesn't show for owner of space

---

src/composables/usePlugins.ts

Fixes confusion due to ambiguous component names.

prefix plugin component names

---

src/components/TextareaArray.vue

Fixes #1609
https://user-images.githubusercontent.com/69431456/152187770-d1720adc-11af-4bb9-9dae-f9caba81e792.mov

fix: duplicate insert in texareaarray component

---

src/components/Plugin/SafeSnap/HandleOutcome.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1549
The issue was that `this.$i18n` wasn't available, leading to "is undefined" errors.. There was probably a simpler fix but mixing options and composition API has its quirks anyway, so I refactored the component entirely, to use `<script setup>`.
@carlosfebres your opportunity to make youreself familiar with the composition API if you haven't already. ;)

[safeSnap] refactored to use script setup syntax

---

src/locales/vi-VN.json

Fixes https://github.com/snapshot-labs/snapshot/issues/1614

Fix bug in VN lang file

---

src/components/Modal/Plugins.vue
src/components/Modal/Validation.vue
src/views/SpaceCreate.vue
src/views/SpaceSettings.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1581
- Use link color for text and border instead of text color
- Show onlyMembers over minScore message
- Changed the Plugins and Validations modal layout to be the same as the Strategies modal
- Hide validation and threshold input if onlyMembers

Show onlyMembers over minScore message and make block more visible

---

src/components/Block/Votes.vue

fix: align tooltip to center in votes list

---

src/components/Voting/Quadratic.vue

fix: don't allow negative numbers in quadratic voting

---

src/components/Modal/Confirm.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1640
- Removing a bug I introduced

Fix voting power not updating after switching wallet

---

src/components/Scroller.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1639
- Add key to Token component for re-rendering

Fix sidebar images not updating

---

src/components/SpaceSidebarHeader.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1673

Fix notifications not showing

---

components.d.ts
src/components/FollowButton.vue
src/components/SelectLanguageButton.vue
src/components/SpaceSidebar.vue
src/components/SpaceSidebarHeader.vue
src/components/SpaceSidebarNavigation.vue
src/components/SpaceSidebarSkeleton.vue
src/router.ts
src/views/Delegate.vue
src/views/Home.vue
src/views/Space.vue
src/views/SpaceAbout.vue
src/views/SpaceCreate.vue
src/views/SpaceProposal.vue
src/views/SpaceProposals.vue
src/views/SpaceSettings.vue

- Space is now always available on all of Space.vue's children
- Added loading and a skeleton sidebar to Space.vue that will show on spaceAbout and spaceProposals routes
- Simplified and renamed the confusing from's
- Removed the need for spaceLoading and spaceId props

Refactor space loading

---

src/views/Space.vue
src/views/SpaceSettings.vue

https://discord.com/channels/707079246388133940/747049240022482974/943191177476321290
- Allow settings to loading with space being available for new spaces

Fix settings not loading when space doesn't exist yet

---

src/views/SpaceSettings.vue

- use spaceKey instead of space.id and space.id is undefined on space creation
- Fix admins not defined error

Fix space creation

---

src/components/Scroller.vue

- Add animation to dragging spacing in scroller

Add sidebar drabble animation

---

src/components/Modal/Confirm.vue

update info link

---

src/views/SpaceSettings.vue

https://discord.com/channels/707079246388133940/831512954435534898/943460389000212520

Fix space settings not loading

---

src/components/SetupController.vue
src/locales/default.json
src/views/SpaceSettings.vue

- Don't show "Edit Controller" button is the wallet isn't the ENSOwner
- Simplify setup button text (remoe space)

Small fixes for settings and setup

---

src/components/Topnav.vue

Fixes #1774
- adding 40px height to the div that pushes the content down

Make spacer div in Topnav higher when there are pending txs

---

src/components/TextareaAutosize.vue
src/views/SpaceCreate.vue

https://github.com/snapshot-labs/snapshot/issues/1768
Couldn't find a good place to put the indicator so I removed it, not really need on the body anyways I think. Also removed some redundant code on the textarea component

Simplify textarea component and remove max length indicator on create

---

src/components/Notifications.vue
src/components/Ui/Calendar.vue
src/components/Ui/Markdown.vue
src/components/Ui/Text.vue
src/style.scss
src/views/SpaceCreate.vue
tailwind.config.js

This time with more descriptive commits

More CSS cleanup and add comments

---

src/views/SpaceCreate.vue

fix error message

---

src/composables/useApp.ts

Fixes https://discord.com/channels/707079246388133940/747049240022482974/946881076553453599
- Show hidden spaces when searched by the exact key

Show hidden spaces when searched by the exact key

---

src/components/TimelineProposal.vue
src/components/TimelineProposalPreview.vue
src/views/SpaceProposal.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1850.

fix: added break-words class to titles

---

src/components/Ui/Input.vue
src/plugins/safeSnap/components/Form/ContractInteraction.vue
src/plugins/safeSnap/components/Form/ImportTransactionsButton.vue
src/plugins/safeSnap/components/Form/RawTransaction.vue
src/plugins/safeSnap/components/Form/TransferFunds.vue
src/views/Playground.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1873
- Fix inputs

Fix inputs

---

src/components/SetupController.vue

change mb-2 to my-2

---

src/composables/useAliasAction.ts

Added a comment, briefly explaining the alias mechanic. I personally ignored this and other related code for a while now, because of the lack of comments/docs. Figured it out now and would like to preserve my new knowledge somewhere. ;D
This should also be explained in the docs somewhere but not sure where.

commented alias composable

---

src/locales/default.json
src/views/SpaceCreate.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1895

Fix voting type enforced

---

src/locales/languages.json

Can be added back when more complete

Remove languages that are at 50% translation

---

src/App.vue
src/components/Modal/Skins.vue
src/components/TheFooter.vue
src/composables/useSkin.ts

- Cleanup and refactor useSkin composable

Fix useSKin

---

src/components/Block/Network.vue
src/components/Block/Plugin.vue
src/components/Block/Skin.vue
src/components/Block/Strategy.vue
src/components/Block/Validation.vue
src/components/Modal/Networks.vue
src/components/Modal/Plugins.vue
src/components/Modal/Skins.vue
src/components/Modal/Strategy.vue
src/components/Modal/Validation.vue
src/views/Explore.vue

- Fix spacing on explore and inside skins, plugins, networks ...

Fix spacing explore

---

src/App.vue
src/components/BaseDropdown.vue
src/components/Block.vue
src/components/Block/Results.vue
src/components/FollowButton.vue
src/components/Modal/Category.vue
src/components/Modal/Skins.vue
src/components/Modal/VotingType.vue
src/components/NavbarNotifications.vue
src/components/RowLoading.vue
src/components/SetupProfile.vue
src/components/SpaceSidebarFooter.vue
src/components/TheFooter.vue
src/components/TheNavbar.vue
src/components/TheSidebar.vue
src/components/Ui/Button.vue
src/composables/useApp.ts
src/composables/useCategories.ts
src/composables/useScrollMonitor.ts
src/composables/useSkin.ts
src/composables/useSpaces.ts
src/plugins/safeSnap/utils/validator.ts
src/style.scss
src/views/Home.vue
src/views/Setup.vue
src/views/SpaceCreate.vue
src/views/SpaceProposal.vue
src/views/SpaceProposals.vue
src/views/SpaceSettings.vue

- renamed `explore.spaces` to just `spaces`
- deleted old code in `useApp`
- re-added `useDomain` in `App.vue`
- ...

useSpaces composable, cleanup/fixes

---

src/App.vue
src/components/BaseMessageBlock.vue
src/components/Block.vue
src/components/Block/Network.vue
src/components/Block/Plugin.vue
src/components/Block/Skin.vue
src/components/Block/Strategy.vue
src/components/Block/Validation.vue
src/components/Modal/VotingType.vue
src/components/ModalControllerEdit.vue
src/components/SetupProfile.vue
src/components/SpaceSidebarHeader.vue
src/components/SpaceSidebarSkeleton.vue
src/components/TheFooter.vue
src/components/TheNavbar.vue
src/components/TheSidebar.vue
src/components/TimelineProposal.vue
src/components/Ui/Button.vue
src/components/Ui/UnreadIndicator.vue
src/composables/useSkin.ts
src/style.scss
src/views/Home.vue
src/views/SpaceAbout.vue
src/views/SpaceProposals.vue
src/views/SpaceSettings.vue

- FIx background on dark mode 
- and more...

Fix more styling

---

src/components/BaseDropdown.vue
src/components/NavbarNotifications.vue

From:
Back to:
Also works left and right now:

dropdown bg/style change, position fix

---

src/components/Block/CastVote.vue

Frontend part of https://github.com/snapshot-labs/snapshot/issues/1972
- Enforce select/rank all choices on ranked choice voting

Fix ranked choice voting calculation

---

src/components/BaseBlock.vue
src/components/Block/Results.vue
src/components/Block/Votes.vue
src/components/TheLayout.vue
src/components/TimelineProposal.vue
src/views/Playground.vue
src/views/SpaceProposal.vue
src/views/SpaceProposals.vue
src/views/Timeline.vue

Fixes #1986.
Everything fixed except:
6. see: https://github.com/snapshot-labs/snapshot/pull/1987

Layout fixes

---

src/App.vue
src/components/TheNavbar.vue
src/components/TheSidebar.vue
src/composables/useApp.ts
src/style.scss

This is not the nicest sidebar mechanic I've ever seen but it does the trick for now.
See [deployment](https://bafybeiaeeivrivyhrnvcfqeuacrnsmjmepbvlijqbb45mx5blnecyg43zq.on.fleek.co/)...

collapse sidebar on small screens

---

src/components/BaseBlock.vue
src/components/BaseButton.vue
src/components/LoadingSpinner.vue
src/components/NavbarNotifications.vue
src/components/SpaceSidebarHeader.vue
src/components/TheFooter.vue
src/components/TheNavbar.vue
src/plugins/safeSnap/components/Config.vue
src/views/Explore.vue
src/views/Home.vue
src/views/SpaceProposal.vue

Fixes #1989.
3. has its own issue: https://github.com/snapshot-labs/snapshot/issues/1980

Layout fixes 2

---

src/composables/useClient.ts

Use typed data for portis as they now have support

fix(): use typed data for portis

---

src/views/SpaceCreate.vue

feat(): store proposal to draft

---

src/helpers/delegation.ts
src/views/Delegate.vue

Fix delegations page bug with new d-graph

---

src/views/SpaceProposal.vue

Some users might use ipfs links as their discussion link, this will add the gateway in those cases

Add url resolver for discussion link

---

src/components/LabelProposalState.vue
src/components/NavbarNotifications.vue
src/components/SpaceSidebarNavigation.vue
src/components/TheNavbar.vue
src/views/SpaceProposal.vue
src/views/SpaceSettings.vue

Fixes # .
- Fix TheNavbar margin bug
- Fix indicator color on notifications

Various bugs

---

src/composables/useEns.ts
src/views/Delegate.vue

```
const res = await ensApolloQuery({
query: ENS_DOMAINS_BY_ACCOUNT_QUERY,
variables: {
id: web3Account.value.toLowerCase()
}
});
```
When `res.account.domains` is `null` I get the following error
I also replaces some `if` `else` nesting with guard clauses to improve readability

Fix delegation page errors

---

src/locales/languages.json

Fixes https://discord.com/channels/707079246388133940/831512954435534898/970714479627218974

Add back french to language selector

---

src/views/SpaceSettings.vue

Changes from stable:
https://github.com/snapshot-labs/snapshot/commit/e500c4e355e1b042bc973f4836df09edbd8d55ef
Reverted to showing separate boxes for Authors and Proposal validation on settings page, as before https://github.com/snapshot-labs/snapshot/commit/6a8b9832d43ec27641d6681ecf4f46ad305232b9.

reverted changes in proposal validation and authors

---

src/locales/default.json
src/plugins/safeSnap/components/HandleOutcome.vue
src/plugins/safeSnap/constants.ts
src/plugins/safeSnap/models.ts
src/plugins/safeSnap/utils/realityModule.ts

If all transactions were not executed before expiring, a message is shown

[safesnap] Display message if execution time expired

---

src/views/Playground.vue

Add addresses with zero score to results

---

src/components/Modal/Strategies.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/1980

Show strategy network and link to block explorer for strategy network

---

package.json
src/components/Block/Network.vue
src/components/Modal/Strategy.vue
src/plugins/safeSnap/components/SafeTransactions.vue
yarn.lock

Merge only after creating new version from https://github.com/snapshot-labs/snapshot.js/pull/576

Fix network logos and delegation subgraph URL change

---

src/components/Modal/Strategies.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/2360

Fix strategies modal links and network

---

src/locales/default.json
src/views/Setup.vue

Fix html in default.json

---

src/views/SpaceCreate.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/2274

Add trim to discussion link v-model

---

src/components/TheSidebar.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/2433

Add counter back to sidebar

---

src/views/SpaceAbout.vue
src/views/SpaceProposals.vue

This move the space about in the main space page

Show about in main page

---

src/components/ProfileAboutDelegate.vue
src/components/ProfileActivityListItem.vue
src/locales/default.json

- Icon color was black on light skin
- Delegations was throwing an error when network wasn't supported

Fix profile vote icon color and delegation 

---

.env
src/helpers/interfaces.ts
src/plugins/quorum/index.ts
src/plugins/safeSnap/components/Config.vue
src/views/Explore.vue
src/views/Playground.vue

Fixes #2422 
Also contains lint changes

Fix playground address checksum issue

---

src/components/SetupController.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/2462

Fix controller setup form

---

src/components/ModalControllerEdit.vue
src/composables/useExtendedSpaces.ts
src/composables/useSpaceController.ts
src/helpers/interfaces.ts
src/views/Space.vue
src/views/SpaceSettings.vue

Part of #1925
Fixes #2452
Changes:
- Fix edit controller placeholder and other bugs with route for ENS address
- Fix settings not reloading after saving settings or edit controller
- Add typescript to settings view

Fix bugs, start refactor settings and add typescript

---

.env
src/components/Modal/UnsupportedNetwork.vue
src/components/SetupController.vue
src/composables/useSpaceController.ts
src/locales/default.json
src/style.scss
src/views/SpaceSettings.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/2423

Rinkeby ENS space

---

src/components/Block/Results.vue
src/components/ModalSpacesListItem.vue
src/components/ResultsItem.vue
src/components/SpaceCreateContent.vue
src/components/SpaceCreateVoting.vue
src/components/SpaceCreateWarnings.vue
src/components/TheSidebar.vue
src/composables/useExtendedSpaces.ts
src/composables/useSpaceCreateForm.ts
src/composables/useSpaceCreateStore.ts
src/helpers/interfaces.ts
src/router.ts
src/views/SpaceCreate.vue
src/views/SpaceSettings.vue

- Bind proposal draft to space id instead of globally
- Refactor SpaceCreate into child component and useSpaceCreateForm composable
- Add typescript 
- Disable the next button when validation is loading

Fix bugs, refactor and add typescript (proposal creation)

---

package.json
src/components/AvatarSpace.vue
src/components/AvatarUser.vue
src/components/BaseAvatar.vue
src/components/BaseUser.vue
src/components/Block/Network.vue
src/components/Block/Plugin.vue
src/components/Block/Votes.vue
src/components/ModalProfileForm.vue
src/components/ModalSpacesListItem.vue
src/components/NavbarNotifications.vue
src/components/PopoverProfile.vue
src/components/ProfileActivityListItem.vue
src/components/ProfileSidebarHeader.vue
src/components/TheNavbar.vue
src/components/TheSidebar.vue
src/components/TimelineProposal.vue
src/components/TimelineProposalPreview.vue
src/plugins/commentBox/components/CommentBlock.vue
src/plugins/commentBox/components/ReplyBlock.vue
src/plugins/safeSnap/components/SafeTransactions.vue
src/views/Delegate.vue
src/views/Playground.vue
src/views/SpaceAbout.vue
src/views/SpaceProposal.vue
src/views/SpaceSettings.vue
yarn.lock

Fixes https://github.com/snapshot-labs/snapshot/issues/2477
Fixes https://github.com/snapshot-labs/snapshot/issues/2476

Fix space avatar 

---

src/components/ButtonLanguage.vue
src/components/TheFooter.vue
src/components/TheNavbar.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/691

Add language switcher on custom domain

---

src/views/SpaceCreate.vue
src/views/SpaceProposal.vue

- Fix snapshot query param issue when going to step 2
- Fix step issue when going back on duplicate proposal
- Fix proposal strategies ui

Fix snapshot issues

---

src/composables/useClient.ts
src/views/SpaceCreate.vue

The strategies are not required anymore in the proposal payload, I'm removing it also to allow Trezor or others hardware wallet users to post proposal with larger content (as these HW have char limit).

Remove strategies from proposal message

---

package.json
src/App.vue
src/composables/useApp.ts

Fixes https://github.com/snapshot-labs/snapshot/issues/2514

Auto connect coinbase wallet

---

src/components/SpaceCreateVoting.vue
src/composables/useDelegate.ts
src/helpers/profile.ts
src/plugins/gnosis/components/CustomBlock.vue
src/plugins/quorum/components/CustomBlock.vue
src/plugins/quorum/index.ts
src/plugins/safeSnap/index.ts
src/plugins/safeSnap/utils/index.ts
src/views/PlaygroundView.vue

Use brovider

---

.github/stale.yml

Create a new label stale to mark stale issues

---

src/locales/ar-SA.json
src/locales/de-DE.json
src/locales/default.json
src/locales/es-ES.json
src/locales/fil-PH.json
src/locales/fr-FR.json
src/locales/id-ID.json
src/locales/it-IT.json
src/locales/ja-JP.json
src/locales/ko-KR.json
src/locales/pt-PT.json
src/locales/ro-RO.json
src/locales/ru-RU.json
src/locales/tr-TR.json

Changes in this PR: Just renamed a type
While creating a space.!

fix: typo in intl

---

src/components/SpaceSidebarHeader.vue

Fix spacing on space sidebar header

---

src/plugins/poap/index.ts

Fixes Issue on POAP side.
The POAP plugin currently checks if the address voted the proposal on page load. This info is used to enable the mint POAP button. Currently this info is obtained via POAP API call (/snapshot/proposal/:snapshot/:address), this endpoint gets the voted info from snapshot API. POAP API is being rate limited by Snapshot API because of this and will be updated to just perform this check before actually minting the voted POAP.
This PR aims to solve this problem by optimizing the way needed info is obtained.
- GET info on whether the address voted the proposal directly from snapshot API instead of from POAP API.
- Run locally, go to a space with the POAP plugin installed, go to a proposal with am associated voted POAP.

Get voted info from own api

---

src/helpers/queries.ts

Fixes https://github.com/snapshot-labs/snapshot/issues/2771

Raise follows query limit

---

src/App.vue
src/components/TheNavbar.vue
src/components/TheSidebar.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/2006

Sidebar improvements

---

src/components/ModalConfirm.vue
src/helpers/queries.ts
src/helpers/snapshot.ts

This is to prepare the change to move delegation as core feature.

Use getVp to get single user voting power

---

src/components/ModalUnsupportedNetwork.vue
src/components/SetupDomain.vue
src/helpers/ens.ts
src/locales/ar-SA.json
src/locales/de-DE.json
src/locales/default.json
src/locales/es-ES.json
src/locales/fil-PH.json
src/locales/fr-FR.json
src/locales/id-ID.json
src/locales/it-IT.json
src/locales/ja-JP.json
src/locales/ko-KR.json
src/locales/pt-PT.json
src/locales/ro-RO.json
src/locales/ru-RU.json
src/locales/tr-TR.json
src/locales/zh-CN.json

Fixes https://github.com/issues/assigned
> !IMPORTANT
Only merge by changing env variables
In demo.snapshot.org
```
VITE_DEFAULT_NETWORK=5
```
In testnet.snapshot.org
```
DEFAULT_NETWORK=5
```

Move to Goerli

---

src/components/ModalUnsupportedNetwork.vue
src/components/SetupDomain.vue
src/helpers/ens.ts
src/locales/ar-SA.json
src/locales/de-DE.json
src/locales/default.json
src/locales/es-ES.json
src/locales/fil-PH.json
src/locales/fr-FR.json
src/locales/id-ID.json
src/locales/it-IT.json
src/locales/ja-JP.json
src/locales/ko-KR.json
src/locales/pt-PT.json
src/locales/ro-RO.json
src/locales/ru-RU.json
src/locales/tr-TR.json
src/locales/zh-CN.json

Reverts snapshot-labs/snapshot#3045

Revert "Move to Goerli"

---

src/plugins/projectGalaxy/README.md

chore: fix typo in projectGalaxy/README.md

---

src/components/ModalConfirm.vue
src/components/SpaceProposalVotesList.vue
src/composables/useClient.ts
src/helpers/interfaces.ts
src/helpers/queries.ts
src/locales/default.json
src/locales/zh-CN.json
src/style.scss

Fixes Issue #3147
* submit vote with reason
* query votes with reason
* display vote reason if not empty
you can vote on any proposal with reason and then check the result.
Screenshot:
Potential related issue:
it seems the API didn't return newest reason after user change their vote option. (newest option but not newest reason).

Add `reason` when cast vote

---

.github/dependabot.yml

Reference https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow

Dependabot for @snapshot-labs/snapshot.js

---

src/components/ModalPostVote.vue

fix: Hide queue transactions button

---

src/components/SetupStrategyBasic.vue

1) Go to `Create a Space` page
2) Under `Strategy` -> `Setup voting strategy` step, select different chain like `Binance Mainnet`. There shouldn't be any console errors or RPC calls to previous node

Moved RPC calls to Brovider URL

---

src/components/SpaceProposalVotesList.vue
src/composables/useReportDownload.ts
src/helpers/queries.ts
src/helpers/snapshot.ts
src/views/SpaceProposal.vue

- Added space to votes query here,
- Also reduced one request to hub, when user's wallet is not connected
```js
web3Account.value
? await getProposalVotes(id, {
first: 1,
voter: web3Account.value,
space: proposal.value.space.id
})
: [],
```

Send space with votes query

---

src/components/BaseSearch.vue

The instant route update was lagging out the spaces search input field when typing. Fix is just adding a debounce with a slight delay. This also fixes all the other searches like strategies and networks.

fix: Space search input lagging 

---

src/components/SpaceSidebarNavigation.vue

Fixes #3368
Fixes #3009
Looks for `delegation` in the name and in the params now.

fix: Delegation navigation not showing

---

README.md
src/components/FooterSocials.vue
src/components/SetupMessageHelp.vue
src/components/SpaceProposalResultsError.vue
src/components/SpaceProposalsNotice.vue
src/components/TheFooter.vue
src/locales/hi-IN.json
src/locales/uk-UA.json
src/locales/vi-VN.json
src/views/AboutView.vue

Discord invite link was invalid as mentioned [here](https://discord.com/channels/707079246388133940/728646188252921956/1050607080786120754).
Update all links to `https://discord.snapshot.org`

Update discord invite link

---

src/components/ModalVote.vue

Fix no voting power

---

src/plugins/safeSnap/constants.ts

Signed-off-by: John Shutt <pemulis@users.noreply.github.com>
Fixes #2814 (partial)
Adds ABI for UMA Finder.
n/a

add finder abi

---

src/components/SpaceCreateVoting.vue
src/components/SpaceCreateWarnings.vue
src/composables/index.ts
src/composables/useSnapshot.ts
src/locales/default.json
src/views/SpaceCreate.vue

Fixes #3447
Learn more links to our DIscord 🦸

fix: Show warning if fetching snapshot fails

---

src/components/MessageWarningVoteValidation.vue
src/components/ModalVote.vue
src/components/ModalVoteValidation.vue
src/components/SpaceAboutStrategiesList.vue
src/helpers/interfaces.ts
src/locales/default.json
src/views/SpaceAbout.vue

Fixes #3452 
- Use the validations endpoint for list of validations instead of hard coding it
- Fix new validation `basic` and add warning message to the voting modal if user doesn't pass <img width="839" alt="image" src="https://user-images.githubusercontent.com/51686767/215121348-90517e0a-f9c7-49a2-8523-94087fafa9fc.png">
- Refactor strategies list in `SpaceAbout` in preparation for adding Vote validation block

feat: Show list of all validations for voting

---

index.html

Fixes #1395
Add description meta tag for homepage

feat: Add meta description for snapshot homepage

---

src/components/SpaceSidebarNavigation.vue

fix: Don't show settings on legacy spaces

---

src/plugins/progress/plugin.json
src/plugins/progress/readme.md

Fixes #
Addition of a Readme file for Progress Plugin
Correcting of Progress Plugin version to be 1.0.0
No changes to code.

Progress Plugin - Readme and Update Version

---

src/components/SpaceProposalPage.vue
src/components/SpaceProposalVote.vue
src/components/SpaceProposalVoteApproval.vue
src/components/SpaceProposalVoteQuadratic.vue
src/components/SpaceProposalVoteRankedChoice.vue
src/components/SpaceProposalVoteSingleChoice.vue
src/views/RankingView.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/3527
- Ensure that user votes are displayed at the top after connecting
- Optimize performance for faster page loading times
- Address several minor issues and enhance the code's readability

fix: Vote doesn't show up on top after connecting

---

src/components/ModalConfirmAction.vue
src/components/SettingsValidationBlock.vue
src/composables/useExtendedSpaces.ts
src/composables/useFormSpaceSettings.ts
src/locales/default.json
src/views/SetupView.vue
src/views/SpaceSettings.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/3581
- Show warning when leaving settings page with unsaved changes <img width="834" alt="image" src="https://user-images.githubusercontent.com/51686767/225494183-b67a769b-859b-4be2-8b5c-8ae327fd6fd4.png">
- Refactor form pruning to no longer interfere with `hasFormChanged` check
- Move validation form population into populateForm to no longer interfere with `hasFormChanged` check
- Fix space reload loading indicators after saving settings

Settings improvements

---

src/components/ExploreSpaces.vue
src/components/ProposalsItem.vue
src/views/TimelineView.vue

fix: Show verified icon

---

src/components/BaseButtonIcon.vue
src/components/ButtonSidebar.vue
src/components/InputSelect.vue
src/components/InputSelectPrivacy.vue
src/components/InputSelectVoteType.vue
src/components/InputSelectVoteValidation.vue
src/components/SettingsDomainBlock.vue
src/components/SettingsPluginsBlock.vue
src/components/SettingsProposalBlock.vue
src/components/SettingsSubSpacesBlock.vue
src/components/SettingsTreasuriesBlock.vue
src/components/SettingsTreasuriesBlockItem.vue
src/components/SettingsValidationBlock.vue
src/components/SettingsVotingBlock.vue
src/components/SpaceCreateVoting.vue
src/views/SpaceSettings.vue

fix: Add view only to all other section

---

src/composables/useFormSpaceSettings.ts

Fix for https://www.loom.com/share/d0c1e5db01f84322aebb1390092149ae

Fix: default to any only if params is empty and when there is no minScore

---

src/components/BaseModal.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/3623

feat: close BaseModal on ESC

---

src/components/SpaceProposalPage.vue
src/components/SpaceProposalPlugins.vue
src/components/SpaceProposalPluginsSidebar.vue
src/components/SpaceProposalVotesList.vue
src/plugins/poap/ProposalSidebar.vue
src/plugins/poap/components/CustomBlock.vue
src/plugins/progress/ProposalSidebar.vue
src/plugins/projectGalaxy/ProposalSidebar.vue
src/plugins/projectGalaxy/components/CustomBlock.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/3624
- removed votes ref from SpaceProposalPage
- removed unused votes props from plugins
- make sure all plugins works good

Remove votes props from plugins

---

src/components/BaseModal.vue
src/components/SpaceProposalPage.vue
src/components/SpaceProposalVotesModal.vue
src/composables/useProposalVotes.ts

Fixes https://github.com/snapshot-labs/snapshot/issues/3641
Fixes https://github.com/snapshot-labs/snapshot/issues/3653
Fixes https://github.com/snapshot-labs/snapshot/issues/3652

fix: search bugs

---

src/components/SpaceProposalsMenuFilter.vue
src/components/TheSearchBar.vue
src/helpers/queries.ts
src/views/SpaceProposals.vue

Fixes https://github.com/snapshot-labs/snapshot/issues/3576
- go to space page and try to search for proposal by title

feat: search bar for proposals

---

src/App.vue
yarn.lock

fixes sidebar on desktop and mobile after tailwind update v3.3
toggle sidebar on mobile and desktop
1. Step 1
2. Step 2

hotfix: sidebar desktop/mobile

---

package.json
yarn.lock

Fixes #
Fixes #
1. Updated snapshot lock library version to accommodate xdefi wallet
1. Step 1
2. Step 2

feat: updated lock library version

---

src/components/SpaceProposalVotesListItem.vue
src/helpers/utils.ts
src/style.scss

Fixes https://github.com/snapshot-labs/snapshot/issues/3676
1. Added props and theme to v-tippy in SpaceProposalVotesListItem.vue
1. Go to proposal with link in tooltip [like this](https://snapshot.org/#/arbitrumfoundation.eth/proposal/0x3be7368a662d1cf12fa4da768d626edbc013be0dc7b994fef2e24d9a54e4033a)
2. Click links

feat: urlify tooltip text

---

src/components/SpaceProposalVotesModal.vue
src/composables/useProposalVotes.ts

Fixes https://github.com/snapshot-labs/snapshot/issues/3631
1. Added resolveLens() to UseProposalsVotes
1. Go to [Arbitrum DAO Proposal](https://snapshot-git-j0hnfl0w-3631-snapshot.vercel.app/#/arbitrumfoundation.eth/proposal/0x3be7368a662d1cf12fa4da768d626edbc013be0dc7b994fef2e24d9a54e4033a)
2. Try to find votes with: 0xf9551c66995eD3Ff9bb05C9Fd7ff148Bd75dc99a, nathanvdh.eth, nathanvdh.lens
3. It should resolve the same voter

feat: add resolveLens

---

src/components/SpaceProposalHeader.vue
src/locales/default.json

Add report button that links to tallyso

---

.gitignore
src/composables/useProposals.ts

Add [scam urls](https://github.com/snapshot-labs/snapshot/pull/3752/files) from latest proposal reports

flags: Add scam urls

---

src/components/SpaceProposalPage.vue

Loom https://www.loom.com/share/22ea29c0f28942f3b16bc215981cb18d
Fixes https://discord.com/channels/955773041898573854/1031838696846131200/1098568780109586482

fix: Remove flag warning modal for message

---

src/components/BlockLink.vue
src/plugins/safeSnap/components/Form/SendAsset.vue

Related to https://github.com/snapshot-labs/snapshot/issues/3723#issuecomment-1516042815
You can test on `gnars.eth` space

Update collectables paths with v2 API

---

src/components/SettingsVotingBlock.vue

So tuneinput return string always
1. Go to any space settings, update quorum input, and try to save the settings, it will throw an error 

Fix quorum input

---

src/locales/default.json

@samuveth small update for the message about using demo.snapshot we discussed before.
With that, I think it would be good to discuss plugging the demo page mention in other places too to address users who don't own a space but are testing proposals.

change demo website message

---

src/plugins/safeSnap/components/HandleOutcomeUma.vue

There was an issue discovered with oSnap transaction execution where only the first transaction is being executed when there are multiple transactions in a batch.
Fixes #
1. This PR makes an update to use `mainTransaction` for each transaction batch.
1. Go through the proposal process with an oSnap proposal and transaction data. Include multiple transactions in a batch.
2. Execute the proposal. 
3. Confirm all transactions have been executed.

fix: Fix issue with batch transactions not being executed

---

package.json
src/composables/useSpaceController.ts
yarn.lock

Require https://github.com/snapshot-labs/snapshot.js/pull/829

Use latest ensResolver

---

package.json
src/components/ModalValidation.vue
src/components/ModalVoteValidation.vue
src/locales/default.json
yarn.lock

1. Simplify Basic vote validation, like proposal validation 
2. Fixed a bug where strategies where defined in params even though not visible on the UI

Simplify basic vote validation and fixes

---

src/components/ModalSelectDate.vue
src/locales/default.json
src/views/SpaceCreate.vue

Reverts snapshot-labs/snapshot#3991

Revert "feat(proposal): add validation to start time"

---

src/components/ModalSelectDate.vue
src/locales/default.json
src/views/SpaceCreate.vue

[#334](https://github.com/snapshot-labs/snapshot-hub/issues/334)
Fixes #
Set starting date not greater than the current time. Restrict users to enter lower time than the current time
1. Create Proposal
2. Try to enter the start date/time lower than the current time

fix(proposal): add validation to start time

---

src/locales/default.json

Doesn't require gitcoin passport validation anymore, basic validation should work too
Fixes #
1. 
1. 

Update message if proposal is missing voting validation while using ticket strategy

---

src/plugins/safeSnap/utils/umaModule.ts

We are seeing "something went wrong" when visiting [this proposal](https://snapshot.org/#/acrossprotocol.eth/proposal/0xb1ad4c7e16b750009becc991297e7a014aaf7f46a4427cb13c61ee08f19e2053)
Fixes #
After some investigation, we have discovered a very rare edge case, when the dao changes their on chain OG rules, we can no longer discover the details for the proposal. There was an assumption baked into the search that the rules would not change. Across recently changed their rules to simplify verification of osnap proposals, which trigged this bug.
1. this changes how we search for the osnap proposal, based on searching the og subgraph for explanation, rather than including the rules.  this new methodology only requires proposal hash, explanation and module address, which should provide unique …

fix: correctly find proposal when on chain rules changed

---

src/components/ModalPlugins.vue
src/components/ModalTreasury.vue
src/components/ModalValidation.vue
src/components/ModalVoteValidation.vue
src/locales/default.json

Fixes https://github.com/snapshot-labs/snapshot/issues/4071
1. Change "Save" to "Apply changes"
2. Fix Treasury modal condition for button naming

fix: Change "Save" button naming

---

src/sentry.ts
vite.config.ts

This PR:
- Create sourcemap and upload them to Sentry on build

chore: enable sourcemap

---

package.json
src/helpers/profile.ts
yarn.lock

Fixes https://discord.com/channels/707079246388133940/1133103494392463501
1. Install and use https://www.npmjs.com/package/@adraffy/ens-normalize
1. Create ENS with `-` as prefix or suffix. Try to create a space

fix: ENS normalize up to date package 

---

src/components/BaseListbox.vue
src/components/BaseSearch.vue
src/components/BaseSidebarNavigationItem.vue
src/components/ButtonFollow.vue
src/components/SpaceDelegatesAccount.vue
src/components/SpaceDelegatesListItem.vue
src/components/TheSidebar.vue
src/components/TreasuryWalletsList.vue
src/views/SpaceAbout.vue
src/views/SpaceDelegates.vue
src/views/SpaceProposals.vue

This is mainly fixing the layout for space delegates page
Other changes:
- Add divider in the sidebar
- Fix delegate card layout
- If not following show Join button as primary, otherwise show delegate/new proposal as primary button

fix: Apply design changes from figma

---

.env
src/components/InputUploadImage.vue
src/composables/useImageUpload.ts

Fixes #
1. add global env for configuring pineapple url
1. should work as before

feat(env): add pineapple url for configuring

---

package.json
yarn.lock

Reverts snapshot-labs/snapshot#4122

Revert "build(deps): bump readable-stream from 3.6.0 to 4.4.2"

---

src/components/PopoverHoverProfile.vue
src/components/ProfileAddressCopy.vue
src/components/ProfileName.vue
src/components/ProfileSidebar.vue
src/components/ProfileSidebarHeader.vue
src/components/ProfileSidebarNavigation.vue
src/components/SpaceDelegatesProfileModal.vue

1. Fix profile sidebar to look like the space sidebar
1. Go to any user profile

fix: Profile sidebar

---

src/components/BlockLink.vue
src/components/SpaceCreateContent.vue
src/components/SpaceProposalPage.vue

1. Add loading state to link preview block
2. No longer show title when discussion link is not resolvable 
3. Add preview block to the discussion link input on proposal creation

fix: Link preview block title and add loading

---

src/components/SpaceProposalVotesListItem.vue

fix(xss): fix vulnerability

---

README.md
src/components/SpaceProposalVote.vue

-
Fixes #
There are warnings in the console related to the wrong passed type to `SpaceProposalVote` component. It happens when the proposal is flagged, then we pass a `null`
1. Fix types of expected arguments in SpaceProposalVote component
1. Open flagged proposal
2. There should be no warnings

fix(warnings): fix browser warnings

---

src/locales/default.json

#4244 
Fixes #
Adds locales to dictionary
1. added a couple of keys
1. Should properly display title and description for Karma validation

fix(locale): add missed key to translations

---

src/views/TimelineView.vue

Requested here https://discord.com/channels/955773041898573854/1030772384308932608/1157650379358621696

fix: Hide flagged proposals from timeline

---

src/views/SpaceProposals.vue

Fixes an issue brought up by some users and Nathan, where space proposals were reloading and forcing the user to scroll down again when coming back from a proposal.
1. Scroll down on space proposals page and then click a proposal. When going back with browser or back button in UI the list should remain as before.
2. You can also test this with spaces that have sub-spaces and switching between the spaces from sidebar. Everything should work as expected.

fix: Prevent refreshing when going back to proposals

---

src/components/SettingsStrategiesBlock.vue
src/components/SetupStrategyAdvanced.vue
src/components/SetupStrategyVote.vue

Fixes: https://github.com/snapshot-labs/snapshot/issues/4276
I've also added fixes for the symbol validation when selecting the "One person one vote" strategy option, fixes both whitelist and ticket option.
1. Try to create a space and don't enter a symbol, see error message on input

fix: Symbol validation for setup vote and advanced

---

package.json
tailwind.config.js
yarn.lock

chore: Update tailwind-prettier package and fix errors

---

package.json
yarn.lock

chore: Remove lint-stages package

---

package.json
src/assets/css/main.scss
src/helpers/constants.ts
src/helpers/vitePlugins.ts
src/main.ts
src/router/index.ts
vite.config.ts

chore: Cleanup various files and refactor 

---

src/views/ExploreView.vue

https://snapshot.org/#/?filter=networks&q=5 If we go here we see all networks including testnets

fix: Hide mainnet networks from networks list

---

src/components/TheFooter.vue
src/locales/default.json

fix: Add feature requests link to footer

---

src/composables/useClient.ts

Remove `reactivate-space` action, which is not used anymore

chore: remove unused action

---

src/helpers/connectors.ts
src/helpers/constants.ts

Adds MetisSafe domain to whitelist
Closes: https://github.com/snapshot-labs/snapshot/issues/4441

Add MetisSafe to KNOWN_HOSTS

---

src/components/MessageWarningTestnet.vue
src/components/ModalUnsupportedNetwork.vue
src/components/SetupDomain.vue
src/helpers/constants.ts

Rename remaining `demo` to `testnet`

chore: rename demo to testnet

---

src/views/DelegateView.vue

Closes: https://github.com/snapshot-labs/snapshot/issues/4471

fix: Border delegations

---

src/components/BaseBadge.vue
src/components/BaseBreadcrumbs.vue
src/components/BaseUser.vue
src/components/LabelProposalState.vue
src/components/ProposalsItem.vue
src/components/SpaceBreadcrumbs.vue
src/components/SpaceProposalHeader.vue
src/components/SpaceProposalPage.vue
src/views/SpaceDelegate.vue

Following the design for proposal page on figma.
Fixes https://github.com/snapshot-labs/snapshot/issues/4478
| Before                | After                 |
|-----------------------|-----------------------|
| <img width="1200" alt="Screenshot 2024-01-06 at 2 45 39 in the afternoon" src="https://github.com/snapshot-labs/snapshot/assets/51686767/1a37d100-8265-403e-ac9b-d1455ba18845">  | <img width="1205" alt="Screenshot 2024-01-06 at 2 45 29 in the afternoon" src="https://github.com/snapshot-labs/snapshot/assets/51686767/c4d03e0f-8a06-4775-9d0e-633e4d3b4180">  |
| Before                | After                 |
|-----------------------|-----------------------|
| <img width="1259" alt="Screenshot 2024-01-06 at 2 56 11 in the afternoon" …

fix(design): Add breadcrumbs to proposal page and fix proposal heading

---

src/composables/useClient.ts

Fix issue where proposal update does not return the receipt, due to an error thrown in mixpanel tracking
Closes: #4504
1. Edit a proposal
2. Submit
3. It should show success notification, and redirect to proposal page

fix: fix invalid payload property

---

README.md

Update Twitter (X) Shield

---

src/components/BlockSpacesListItem.vue
src/components/ExploreSpaces.vue
src/components/IconVerifiedSpace.vue
src/components/ModalSpacesListItem.vue
src/components/ProfileAboutDelegateListItem.vue
src/components/ProposalsItem.vue
src/components/SpaceSidebarHeader.vue
src/helpers/interfaces.ts
src/helpers/queries.ts

feat: highlight turbo space icon

---

src/assets/css/main.scss
src/components/Tune/TuneButton.vue

fix: button primary color to black and white

---

src/components/ProfileSidebar.vue

"Edit profile" button is missing, due to addresses comparison failing because of character case
1. Go yo your profile
2. The edit profile button should appear in the sidebar

fix: fix missing edit profile button

---

src/components/SettingsTreasuryActivateOsnapButton.vue
src/plugins/oSnap/Create.vue
src/plugins/oSnap/Proposal.vue
src/plugins/oSnap/components/BotSupportWarning.vue
src/plugins/oSnap/types.ts
src/plugins/oSnap/utils/getters.ts

We want to let the user know if their transaction will auto execute by UMA infrastructure
Closes: #
1. go to an osnap supported space
2. make a proposal
3. check transaction builder to see if transaction is configured to be auto executed by bot. it should be true if osnap is configured using WETH and 2.0 bond size.

feat: osnap execution warning message snapshot

---

src/assets/css/tune.scss
src/components/SettingsBoostBlock.vue
src/components/SpaceProposalBoost.vue
src/components/SpaceProposalPage.vue
src/composables/useBoost.ts
src/composables/useFormSpaceSettings.ts
src/helpers/boost/index.ts
src/helpers/interfaces.ts
src/helpers/queries.ts
src/views/SpaceBoost.vue
src/views/SpaceProposals.vue
src/views/SpaceSettings.vue

feat: Add settings for boost 

---

src/helpers/boost/index.ts

Add boost testers

---

src/composables/useClient.ts

Prints error message in error notification
Context: https://discord.com/channels/955773041898573854/1221106380300357804/1221129598222471179

fix: Error message on notification

---

src/composables/usePayment.ts
src/views/PaymentNetwork.vue

Context: https://discord.com/channels/955773041898573854/1182427601046884352/1222223120828727476

fix: Disable six months payments for network

---

src/locales/default.json

| Before    | After |
| -------- | ------- |
| <img width="698" alt="Untitled 2" src="https://github.com/snapshot-labs/snapshot/assets/15967809/51d830aa-a0cb-46ca-bcc7-1efee94540b3">  |  <img width="733" alt="Untitled 3" src="https://github.com/snapshot-labs/snapshot/assets/15967809/e9e225f7-f059-43a2-9bd5-ec486005c206"> |

fix: Demo URL is wrong and change testnet name

---

src/plugins/domino/components/CustomBlock.vue

fix: Remove color change on hover for domino plugin

---

src/plugins/oSnap/components/Input/SelectSafe.vue
src/plugins/oSnap/components/TransactionBuilder/ModalSafe.vue
src/plugins/oSnap/constants.ts
src/plugins/safeSnap/constants.ts

We aim to support the Base network in Osnap.
1.  In a Snapshot space with a treasury in Base, configured with the Osnap module, create a new vote on the Base network to transfer an amount of tokens from the Safe (treasury) to an address.
2.  Verify that the Tenderly simulation of the transactions on the Base network works properly.
3.  Vote for and wait for the vote to finalize.
4.  After the vote is approved, execute the transactions with Osnap and verify that they work correctly.

Osnap support base

---

src/composables/useTreasury.ts

fix: use the updated url for treasury token list

---

src/views/Network.vue

- Use IPFS images
- Add sei network
- Remove unused css 
1. Go to /#/network page
2. Should use IPFS images

fix: Use IPFS images on network page

---

src/helpers/constants.ts

See https://discord.com/channels/955773041898573854/1182427601046884352/1262724884530987029

fix: whitelist worldassociation.org for iframe

---

src/composables/useClient.ts
src/composables/useStatement.ts
src/helpers/queries.ts
src/views/SpaceDelegate.vue

Fix delegation statement not saving, due to missing required fields
1. Go to your delegation profile on a space with delegation
2. Save the statement
3. It should save

fix: fix statement not saving

---

src/composables/useStrategies.ts

style: fix lint errors

---

README.md

Replaced the link that did not work
Closes: #
1.

Docs: (Update README)

---

src/helpers/connectors.ts
src/helpers/constants.ts

Same as https://github.com/snapshot-labs/sx-monorepo/pull/976

fix: Allow snapshot in fantom safe and add fantom networks to WC

---

src/helpers/constants.ts

- White list apechain safe
1. Create a safe on https://safe.apechain.com/
2. Should open snapshot as an app

fix: whitelist apechain safe

---

src/plugins/progress/readme.md
src/plugins/projectGalaxy/README.md

1. `incentive` → `incentivize`
- Reason: "Incentivize" is the correct verb form to express encouraging or motivating behavior, while "incentive" is a noun.
2. `campain` → `campaign` (in JSON examples)
- Reason: Corrected spelling of "campaign" which is the standard English spelling for this word. This ensures proper functionality as incorrect spelling could cause implementation issues.
1. `Authetication` → `Authentication`
- Reason: Fixed the spelling of "Authentication" which is the correct technical term for web3 identity verification.
2. `notificatiosn` → `notifications`
- Reason: Corrected typographical error in the word "notifications" to improve readability and professionalism of the documentation.

 Fix typos and improve documentation clarity

---

src/components/SetupDomain.vue
src/locales/default.json

Fixes the url links to sepolia testnet playground
Closes:  #4954
1. Described in the related issue

fix: changed the url to the actual testnet env, update i18n

---

src/components/SpaceProposalVotesItem.vue

Same as https://github.com/snapshot-labs/sx-monorepo/pull/1112

fix: Update signator URL path

---

package.json
src/helpers/connectors.ts
yarn.lock

Same as https://github.com/snapshot-labs/sx-monorepo/pull/1152

chore: update coinbase sdk
