src/namespaces.json
rename LAO space for "LAO Community" purposes (small nitpick :pray: )
=> Rename namespace for 'LAO Community'

src/views/Proposals.vue
Currently the only way to make a proposal not show up outside of min token balance is to add the hash to invalids in the namespace. If Core dev wants to hide one of their proposals because of an issue with it, they can't because 'core' returns before 'invalid' in the filter process.
This PR adds a test such that if a proposal is invalid, it wont show up in Core.
=> Allow filtering invalid on Core

src/helpers/networks.json
web socket url for ThaiChain (chainId 7): "wss://ws.dome.cloud"
block explorer url for ThaiChain (chainId 7): "http://exp.tch.in.th"
Fixes # .
- 
- 
-
=> add web socket, block explorer url for ThaiChain

src/components/Plugin/Gnosis/Block.vue, src/views/Proposal.vue
- Add the text of the different choices to Gnosis Impact block with `_shorten` method in case the text is too long.
- Add title choices on div.
=> Add choices text in Gnosis Impact plugin

src/components/Modal/Plugins.vue, src/components/Plugin/Gnosis/Block.vue, src/components/Plugin/Gnosis/Config.vue, src/views/Proposal.vue
- Replace tokenPairQuery from getting array values to compare object
values with `token0Price` and `token1Price` Uniswap-V2 fields https://github.com/snapshot-labs/snapshot.js/pull/49.
- Replace `this.web3.network.key` to `space.network`. This will fix to ask for the right network id from the given space instead look for the network based on the Metamask user wallet. https://github.com/gnosis/snapshot/issues/1.
- Add loading to Gnosis Impact block https://github.com/gnosis/snapshot/issues/2.
Resolves: https://github.com/gnosis/snapshot/issues/1, https://github.com/gnosis/snapshot/issues/2
Require: https://github.com/snapshot-labs/snapshot.js/pull/49
=> Add space.network to Gnosis plugin

src/components/Ui/Calendar.vue
- Calendar showing the current year (2020) always
- Made it get Year based on the month selected
before: 
after:
=> Calendar Year fix - always showing current year

src/views/Settings.vue
There's a broken link present under the /settings page for a space.
=> Fix broken link for custom domain documentation

.github/workflows/nodejs.yml, package-lock.json, package.json, src/shims-vue.d.ts
Fixes #198 
- package-lock is not correct
Also fixes
- Vue CLI Notice 
```
Vue CLI now supports Vue 3 by default.
vue-cli-plugin-vue-next is no longer needed, please remove it from the dependencies.
```
- Error https://stackoverflow.com/questions/62216862/error-in-vue3-argument-of-type-typeof-import-dist-vue-is-not-assignabl
```
ERROR in src/main.ts:17:23
TS2345: Argument of type 'typeof import("snapshot/node_modules/vue/dist/vue")' is not assignable to parameter of type 'Component<any, any, any, Record<string, ComputedGetter<any> | WritableComputedOptions<any>>, MethodOptions>'.
Type 'typeof import("snapshot/node_modules/vue/dist/vue")' is not assignable to type 'ComponentOptions<any, any, any, Record<string, ComputedGetter<any> | WritableComputedOptions<any>>, MethodOptions, any, any, …
```
=> Package-lock file build issue and fix to two notices

src/components/Plugin/Gnosis/Config.vue, src/components/Plugin/Gnosis/CustomBlock.vue, src/views/Proposal.vue
Add network on the Gnosis Impact plugin form to select from which markets would you like to base your proposal. In case you select the network xDai, the Omen markets will come from the xDai network.
- Add default value to `input.network` as Mainnet.
=> Add xDai network support for Gnosis Impact plugin

src/views/Timeline.vue
Stops filter from resetting to `all` on route change.
=> Move filter state outside setup to make it persistent 

src/components/Modal/Networks.vue, src/components/Modal/Plugins.vue, src/components/Modal/Skins.vue, src/components/Modal/Strategy.vue, src/helpers/utils.ts, src/views/Settings.vue
@bonustrack instead of switching the whole component to the CAPI, which would easily create another huge PR mess, I think we could move part by part (like I did here). This way we can focus on each part separately and keep things organized.
=> Use composable filters instead of helper filters

src/components/Plugin/SafeSnap/CustomBlock.vue, src/components/Plugin/SafeSnap/Modal/OptionApproval.vue
There is a bug where, if a DaoModule has a different `minimumBond` than 0.01 ETH (i.e: 0.2 ETH) - We were not showing the correct bond to set (when there's none), now we are showing the `minimumBond` as expected
=> Fix: First set bond bug fix

src/components/Block/Results.vue
Looks like an issue with 
```choice.choice.length > 12 && choice.choice```
Assumed this condition is added to not to show a tooltip when length is less that 12
=> Fix for "false" in tooltip

src/components/Ui/Select.vue
the defineEmits functions is used as an array instead of a function (parentheses and brackets got inverted).
=> [fix] Select Component - defineEmits used an array instead of a function

src/views/Proposal.vue
The exported file name is now generated as `snapshot-report-undefined` fixed it to have proposal id in it instead of `undefined`
You can test it after merging #520
=> Fix exported filename have undefined

src/views/Strategy.vue
Right now when we click on version number in strategy page it redirects to old repository
=> Fix repo name for strategies

src/views/Proposal.vue
If you click to open a proposal then click on the snapshot logo before proposal load it will send you back to the proposal after proposal load.
=> Fix proposal redirection

src/components/Plugin/SafeSnap/Form/Transaction.vue
In SafeSnap's transaction view, the transaction titles are misleading for ERC20 and NFT transfers. Instead of the recipient's address it renders the token contract address:
This PR fixes it.
=> fix(SafeSnap): show correct recipient addresses for transactions

src/components/FollowButton.vue
@bonustrack  for follow terms to work on the Home we need to have the terms available inside explore endpoint. Currently it will just let you follow without accepting the terms.
=> Fix terms modal showing when space has no terms set

src/components/TheSidebar.vue, src/components/Ui/UnreadIndicator.vue, src/composables/useUnseenProposals.ts, src/views/Space.vue, src/views/Timeline.vue
- refactor condition to handle unseen proposals for each space.
- refactor unreadIndicator to a component
- added a comment when the unseen proposals could break
- instead of saving the created time of last proposal for space, saving the current timestamp of the user.
- remove lastSeenProposalId as it is useless
Fixes #645
=> feat(): display unread indicator for timeline.

src/components/TheSidebar.vue
Fixes #654 
I just managed to use the same vertical space found for top icons on Sidebar and used on bottom elements.
=> #654 Use same margins for all icons on Sidebar

src/components/Block/Space.vue, src/views/Home.vue
Fixes #667 
Fixes #677 
- change `$tc('members', space.followers)` to `$tc('members', space.followers, {  count: _n(space.followers)  })`
=> formatted numbers for members count

package.json, yarn.lock
Fixes # .
- Bump vite.js version to ^2.6.0-beta.2
=> feat: bump vite version to ^2.6.0-beta.2

src/components/Icon.vue, src/components/Ui/Dropdown.vue
Fixes #814
- remove `vertical-align: baseline` for `.iconfont` (default anyway)
- overwrite in dropdown with tailwind class `align-middle`
=> fixed icon alignments

package.json, vite.config.ts, yarn.lock
Fixes:
- replaced `vite-plugin-components` with `unplugin-vue-components`
- removed `deep: true` since it's default
=> updated vite-plugin-compnents package

src/components/Plugin/SafeSnap/HandleOutcome.vue, src/components/Plugin/SafeSnap/SafeTransactions.vue, src/composables/useWeb3.ts, src/locales/default.json
Fixes https://github.com/snapshot-labs/snapshot-plugins/issues/12.
Now that we support multiple Safes on different networks, users need to be connected to the right network when submitting oracle transactions or requesting execution of the transactions. This PR improves the UX by:
- auto-switching to the correct network when using MetaMask
- showing a hint "Switch your wallet to `NAME OF CHAIN` to request execution" when using another wallet
=> SafeSnap: switch to right network when requesting execution

src/helpers/connectors.json
- Users are having trouble using the right connector for Trezor because the connector is at the bottom of the modal. In this PR we move it to 2nd position under Metamask.
=> Move Trezor connector up inside connector modal

src/composables/useSpaceSubscription.ts, src/helpers/beams.ts
Fixes page not loading for browser without service worker support.
The pusher beams package performs a check for service worker support (`"serviceWorker" in navigator`) when initializing the client. I put that initialization in a try-catch block to swallow the error.
=> hot fix for browsers without service worker support

src/components/Modal/Category.vue, src/helpers/queries.ts, src/locales/default.json, src/views/SpaceSettings.vue
Fixes #816
- Category modal with multiselect.
scenarios:
1) when you click on confirm, applies the pre-selected categories
2) clicking cancel just closes the modal window
- In space settings page add space categories with displaying the selected categories
- default locales for categories
- add categories in graphQL query
=> fix: space categories params

src/composables/useDomain.ts, src/router.ts
If on localhost, you can test the single space view by setting `VITE_VIEW_AS_SPACE` in `.env.local`.
=> Allow to view UI as if accessed through custom domain

src/components/Block/Network.vue, src/components/Block/Plugin.vue, src/components/Block/Strategy.vue, src/style.scss, src/views/Home.vue
Add hover border effect to spaces, networks, strategies and plugins as part of this https://github.com/snapshot-labs/snapshot/issues/1000
test it in localhost
- Spaces
- Networks
- Strategies
- Plugins
@bonustrack
=> Add border hover effect to spaces, networks, strategies

src/components/Block/Votes.vue, src/composables/useProfiles.ts, src/views/Delegate.vue, src/views/SpaceAbout.vue, src/views/SpaceProposal.vue, src/views/SpaceProposals.vue, src/views/Timeline.vue
Fixes #1036 
The `updateAddressArray` function in `Votes.vue` was called only when the number of votes to show in the list changed, thus on click on "see more". Now also watching votes array itself, so it runs after they are loaded initially.
=> watch votes array to catch initial load

src/views/SpaceSettings.vue
As suggested here: https://github.com/snapshot-labs/snapshot.js/pull/420
Would allow to set `VITE_DEFAULT_NETWORK=4` and use a Rinkeby ENS domain to create a space.
=> Use network env var in getSpaceUri

src/locales/default.json, src/locales/es-ES.json, src/locales/fil-PH.json, src/locales/ja-JP.json, src/locales/pl-PL.json, src/locales/sh-HR.json, src/locales/te-IN.json, src/locales/th-TH.json
Updated multiple locales
- Instead of ``Your POAP is on your address say`` --> ``The POAP has been minted to your collection``.
- Instead of ``Claim your I voted POAP`` say --> ``Mint`` , same as in button below.
- Instead of ``The POAP is being added to your collection`` say --> ``The POAP is being minted to your collection``
=> 💬 Text: Copy updates

src/components/Block/Votes.vue, src/views/SpaceProposal.vue
For proposals with `state != 'final'` `votes.value` was assigned twice, triggering watchers multiple times.
**The general rule here I think is: You should avoid assigning temporary values to properties that are meant to be displayed. If something's temporary, keep it local and don't render it.**
Also for the `visibleVotes` watcher, the existing property is used now, instead of slicing `sortedVotes` twice.
=> avoid redundant prop update

src/locales/ar-SA.json, src/locales/bn-BD.json, src/locales/cs-CZ.json, src/locales/da-DK.json, src/locales/de-DE.json, src/locales/default.json, src/locales/es-ES.json, src/locales/fi-FI.json, src/locales/fil-PH.json, src/locales/he-IL.json, src/locales/hi-IN.json, src/locales/id-ID.json, src/locales/it-IT.json, src/locales/ja-JP.json, src/locales/ko-KR.json, src/locales/mr-IN.json, src/locales/nl-NL.json, src/locales/pl-PL.json, src/locales/pt-PT.json, src/locales/ru-RU.json, src/locales/sh-HR.json, src/locales/sv-SE.json, src/locales/te-IN.json, src/locales/th-TH.json, src/locales/tr-TR.json, src/locales/uk-UA.json, src/locales/ur-IN.json
Updated multiple locales
Instead of ``Mint`` (in header) say --> ``Mint your I voted POAP``.
Instead of ``Claim`` (in button) say --> ``Mint``
Instead of ``Congratulations! The POAP has been minted to your account`` say --> ``Congratulations! The POAP has been minted to your collection``
=> 💬 Text: More Copy updates

src/components/Ui/Dropdown.vue
Allows custom HTML for items.
```html
<UiDropdown :items="[...]">
<UiButton>
My Button
</UiButton>
<template v-slot:item="{ item }">
{{ item.text }}
<span class="badge">{{ item.count }}</span>
</template>
</UiDropdown>
```
The item slot defaults to what it was before:
```html
<Icon
v-if="item.icon"
:name="item.icon"
size="21"
class="align-middle mr-2"
/>
{{ item.text }}
```
Second change: If an item has a `selected` property, it now adds a `selected` class to the `<li>`, sharing same style with hover state.
E.g.:
```html
<UiDropdown
:items="[
{ text: $t('proposals.states.all'), action: 'all', selected: filterBy === 'all' },
...
}"
>
```
=> Dropdown improvements

src/helpers/abi/utils.ts
@rmeissner mentioned that delegate calls don't need transaction value. So we can just hardcode this to 0.
=> Delegate Call does not need transaction value.

src/components/Block/Results.vue, src/helpers/queries.ts, src/locales/default.json, src/views/SpaceSettings.vue
Fixes #1120
Hub PR: https://github.com/snapshot-labs/snapshot-hub/pull/203
`hideAbstain = false`
`hideAbstain = true`
Using multiple strategies (2x `eth-balance`) to see the split progress bar.
=> Basic voting "hide abstain" option

src/components/Modal/Account.vue
Use `space-y-2` instead of `mb-2` which also removed extra space below the logout button
**Before**
**After**
=> chore: use `space-y-2` instead of `mb-2`

src/components/Block/Space.vue, src/components/Block/Votes.vue, src/components/Plugin/CommentBox/Comment.vue, src/components/Plugin/CommentBox/CommentBlock.vue, src/components/Plugin/CommentBox/CustomBlock.vue, src/components/Plugin/CommentBox/ReplyBlock.vue, src/components/Scroller.vue, src/composables/useFollowSpace.ts, src/composables/useSpaceSubscription.ts, src/composables/useUsername.ts, src/composables/useWeb3.ts, src/views/Delegate.vue, src/views/SpaceCreate.vue, src/views/SpaceProposal.vue, src/views/SpaceProposals.vue, src/views/SpaceSettings.vue, src/views/Timeline.vue
Reduces code duplication a bit.
`const web3Account = computed(() => web3.value.account);` was repeated in several components/composables. Moved it to the `useWeb3` composable.
=> move computed web3Account to useWeb3 composable

src/components/Ui/Dropdown.vue
Fixes #1268
- Added z-index for the `sub-menu-wrapper`
=> Added zIndex for timeline dropdown menu

src/components/Plugin/Hal/CustomBlock.vue, src/components/Plugin/config.json, src/components/ProposalPluginsSidebar.vue, src/locales/default.json
Fixes # .
- integrate HAL Plugin on the Snapshot UI
To integrate HAL on the Snapshot UI, so that users can set up a trigger to notify them when a proposal is created or ends for a any given space and receive notifications over email, Telegram, Discord, Slack, or connect it to webhooks to create further automation.
1. User on the Snapshot website wants to be notified when a proposal is created or ends for a specific space.
2. User gets redirect to a custom made recipe on the HAL website, e.g. https://9000.hal.xyz/recipes/snapshot-follow-new-proposals?space-id=test3.shot.eth&status=end.
3. All fields in the recipe are already pre-filled and a custom template is ready to be used right away. The users choose the relevant action (Email, Telegram etc).
4. …
=> Enabling Hal Plugin

src/App.vue, src/composables/useApp.ts, src/helpers/queries.ts
Fixes https://github.com/snapshot-labs/snapshot/issues/1437
- Remove dependence on explore for skins
- Query space skin on init if custom domain
- Remove redundant space var from `useApp`
- Don't show loader until skinName is defined
=> Remove dependence on explore for skins

src/views/SpaceSettings.vue
Space settings doesn't show up for new ENS names (users are not able to save a new space)
=> Fix new space issue

src/components/SpaceSidebarHeader.vue, src/helpers/queries.ts
Fixes https://github.com/snapshot-labs/snapshot/issues/1467
Requires https://github.com/snapshot-labs/snapshot-hub/pull/233
- Use the new `followerCount` on space query instead of explore
=> Use space query instead of explore for follower count

src/views/SpaceSettings.vue
There is an issue with `followerCount` field added here https://github.com/snapshot-labs/snapshot/pull/1475/files
To reproduce go to a space that has followers and save settings, It won't allow saving space, it shows the following error:
=> Space settings fix for followerCount

.github/workflows/update-snapshot-packages.yml
Right now updating a GitHub package with yarn (lock repo) updates all the packages on yarn.lock, so for now it is better to gt updates only from snapshot.js
#1506
=> Remove automatic updates from lock package

src/components/Block/Results.vue, src/components/Block/Votes.vue, src/components/Modal/Confirm.vue, src/components/SpaceSidebarHeader.vue, src/components/Voting/Quadratic.vue, src/locales/default.json, src/style.scss
Fixes https://github.com/snapshot-labs/snapshot/issues/1527 and https://github.com/snapshot-labs/snapshot/issues/1526
- Remove html increment button on firefox 
- Fix RCV and weighted voting alignments
- Fix confirm modal choice string length and show tooltip
Before:
After:
- Fix choice string not filling up available space in multiple components on proposal page
Before - After
=> Proposal spacing and alignments 

src/components/Plugin/SafeSnap/Config.vue, src/components/Plugin/SafeSnap/HandleOutcome.vue
**:warning: [THIS PR](https://github.com/snapshot-labs/snapshot-plugins/pull/66) IN THE [SNAPSHOT-PLUGINS REPO](https://github.com/snapshot-labs/snapshot-plugins) NEEDS TO BE MERGED FIRST :warning:**
Changing the multi-send contract logic and setting by default the newest version of the contract, causes some retro-compatibility errors.
To avoid this, multi-send transactions are also stored in IPFS and some logic was added to support older version.
now all versions should work properly.
=> [snapshot] make static call (avoid hash calculation)

src/views/SpaceSettings.vue
Did really nobody ask for this yet?
Just wrapped it in a `<div class="lg:fixed lg:w-[300px]">`.
=> fixed position for actions block on settings page

src/components/Plugin/SafeSnap/Form/ContractInteraction.vue, src/components/Plugin/SafeSnap/Input/ArrayType.vue, src/components/Plugin/SafeSnap/Input/MethodParameter.vue, src/helpers/validator.ts
**:warning: [THIS PR](https://github.com/snapshot-labs/snapshot-plugins/pull/68) IN THE [SNAPSHOT-PLUGINS REPO](https://github.com/snapshot-labs/snapshot-plugins) NEEDS TO BE MERGED FIRST :warning:**
As described in this issue https://github.com/snapshot-labs/snapshot-plugins/issues/65, creating contract interactions using functions with a tuple as a param was not possible.
This PR adds logic to handle tuples as params.
=> [safesnap] pass tuple params for contract interactions

src/plugins/gnosis/CreateSidebar.vue, src/plugins/safeSnap/Create.vue, src/views/SpaceCreate.vue
If you duplicate a proposal, the plugin form components must wait for that proposal data to be loaded. I simply wasn't aware (enough) of that feature. 🙈
=> Fixed plugin data not loaded when duplicating a proposal

src/components/Block/ResultsError.vue, src/components/Modal/Confirm.vue, src/components/Modal/RevokeDelegate.vue, src/components/NoResults.vue, src/components/Plugin/CommentBox/Comment.vue, src/components/Plugin/CommentBox/CommentBlock.vue, src/components/Plugin/CommentBox/CustomBlock.vue, src/components/Plugin/CommentBox/ReplyBlock.vue, src/components/Plugin/SafeSnap/HandleOutcome.vue, src/components/SearchWithFilters.vue, src/components/TimelineProposalPreview.vue, src/composables/useClient.ts, src/composables/useCopy.ts, src/composables/useI18n.ts, src/composables/useSharing.ts, src/composables/useSpaceSubscription.ts, src/helpers/utils.ts, src/views/Delegate.vue, src/views/Explore.vue, src/views/Home.vue, src/views/Playground.vue, src/views/Setup.vue, src/views/SpaceAbout.vue, src/views/SpaceCreate.vue, src/views/SpaceProposal.vue, src/views/SpaceProposals.vue, src/views/SpaceSettings.vue, src/views/Strategy.vue, src/views/Timeline.vue
I'm currently trying [vitest](https://vitest.dev/) and that requires some cleanup work here and there it seems, or in other words... reveals the messy parts in our code. :-]
To avoid the naming conflict between the `useI18n` composable from the `i18n` plugin and our own `useI18n` composable, the `t` function is now exported from there, so we need only our own one in the components that use that function.
Then I moved the `setPageTitle` function over there too, because it depends on localization and therefore state and should be in a composable instead of utils. Later, when we implement more html meta info stuff, we might want to move it to a `useMetaInfo` composable. For now, this function must accept its new home. :D
So... lots of files but always the same change.
=> export t() from useI18n compoable and moved setPageTitle to it

src/components/SetupController.vue, src/locales/default.json, src/views/Setup.vue
Issue https://github.com/snapshot-labs/snapshot/issues/1801
- Add back "or, Go to settings" button incase user gets stuck like we have the case linked in https://github.com/snapshot-labs/snapshot/issues/1801. This isn't optimal, but seems like an acceptable fix until we have reworked some more of our setup flow. I also want to note that this will only show if the text-record has already been set. <img width="1217" alt="image" src="https://user-images.githubusercontent.com/51686767/155102915-4e0d71d3-daf4-48bb-86ac-f4899f55f89e.png">
- Remove not really needed tooltip. About the same text is shown when there are no registered ENS domains for the connected wallet.
- Remove input label that wasn't really needed and was using a lot of space and instead made it more clear in the block title
=> Improve space setup

src/components/TimelineProposal.vue, src/components/TimelineProposalPreview.vue
Fixes #1806.
There's a [bug in remove-markdown](https://github.com/stiang/remove-markdown/issues/52) causing this.
I couldn't find anything but in case someone complains now about too short preview texts or weirdly cut-off things, we can slightly increase the character count for shortening before calling `removeMd` (280).
=> workaround for bug in remove-markdown

src/helpers/ens.ts
I still think the name `DEFAULT_NETWORK` isn't super appropriate but the space creation works now with Rinkeby ENS domains when set to `'4'`
https://github.com/ensdomains/ens-subgraph/issues/41#issuecomment-1048268488
=> add ens rinkeby subgraph support

src/views/SpaceProposal.vue
**Bug:** When a modal opens the `body` has `overflow: hidden` so that the scrollbar doesn't show and you can't scroll the content in the background. After casting a vote, the confirmation modal disappears, the proposal reloads but you can't scroll because the `body` still has `overflow: hidden`.
**Cause:** [Here](https://github.com/snapshot-labs/snapshot/pull/1809/files#diff-db5facacb5eb9842e03054e4e4244ef5eb435893a4d180bca83b353d9c9d13fcR80) I set the `loading` prop back to true whenever we re-`loadProposal`. What I didn't deem harmful was that the modals on the proposal page aren't rendered while it's true. But since [here](https://github.com/snapshot-labs/snapshot/blob/08d12232edf2080bea3df6edf7100984a66f50df/src/components/Modal/Confirm.vue#L48-L49) the `reload` event is being …
=> fix missing scrollbar after voting

.gitmodules, src/components/Block/Plugin.vue, src/plugins/commentBox/plugin.json, src/plugins/hal/plugin.json, src/plugins/poap/plugin.json, src/plugins/quorum/plugin.json, src/plugins/safeSnap/components/Input/ArrayType.vue, src/plugins/safeSnap/components/Input/MethodParameter.vue, src/plugins/safeSnap/utils/validator.ts
- I removed some old references to snapshot-plugins that were still there ("learn more" links to github)
- then removed the actual submodule
- and also moved `src/helpers/validator.ts` to the safeSnap plugin directory
=> Removed snapshot-plugins submodule

src/components/Modal/UnsupportedNetwork.vue, src/components/ModalControllerEdit.vue, src/components/SetupController.vue, src/composables/useSpaceController.ts, src/composables/useWeb3.ts, src/locales/default.json, src/router.ts, src/views/Setup.vue, src/views/SpaceSettings.vue
This is the first step in decoupling the space settings from the setup flow  https://github.com/snapshot-labs/snapshot/issues/1902
- Move controller logic into composable and create an edit controller modal for settings page
- Prepair setup flow for step 3 (space profile)
- Remove redundant warning and conditional text
=> Remove edit controller from setup flow

src/plugins/safeSnap/components/Form/TransferFunds.vue, src/plugins/safeSnap/components/SafeTransactions.vue, src/plugins/safeSnap/constants.ts, src/plugins/safeSnap/utils/index.ts
As reported in issue #1906, the input amount for tokens wasn't formatted correctly.
what really caught my attention was @ChaituVR 's [comment](https://github.com/snapshot-labs/snapshot/issues/1906#issuecomment-1061868087) saying:
> Something is wrong with transaction data and its hashes, the hash is null
Digging into what could have gone wrong, I found out that the default multi-send contract for an old configuration (`v1.1.1`) was not deployed to Polygon, returning `undefined` instead of the address. What caused **the hash to be null** is that the `to` field in the `main transaction` of the batch is `undefined` making the transaction invalid, so the hash could not be calculated.
If the `v1.1.1` version of the multi-send contract is not available in the network, the `v1.3.0` is used …
=> [safesnap] Fix input amount & MultiSend address for Polygon

src/plugins/safeSnap/components/HandleOutcome.vue, src/plugins/safeSnap/components/SafeTransactions.vue, src/plugins/safeSnap/constants.ts, src/plugins/safeSnap/index.ts
To get the oracle's answers, we need to get the events emitted by the oracle. Chain providers tend to have a block limit, which only returns the events of the last X blocks. To avoid fetching from the genesis block, we set a block to start from per chain (usually the block in which the oracle was deployed).
- As the chain grows, the block eventually will become too old, falling behind the limit.
- Some chains didn't have a block set, so the genesis block was being used, triggering the limit error.
Since we're getting the answers of a question, and a question is created for every proposal. We could get the events dispatched after the proposal's snapshot block since it's a block older than the block in which the question is created.
=> [safesnap] Chain provider reaches block limit

src/views/SpaceProposals.vue
Fixes duplicate proposal showing up. I guess based on some false assumption I added this `!firstProposal ||` which causes the error. Removed it again.
=> fix duplicate proposal issue

src/components/SpaceProposalsNotice.vue
Issue:
- Add background to notice
=> Fix content from behind showing on space notice

src/components/SearchWithFilters.vue
Fixes:
- just made the `routeQuery` default to string
=> fix vue warning

src/App.vue, src/views/Home.vue
Fixes:
- moved `TheFooter` component back to `App.vue` to keep it in it's proper position in the layout
- made rendering depend on route (could become `showFooter` composable if we decide to show it on more than just the home page)
=> moved footer back to App.vue and made rendering depend on route

src/style.scss
Fixes:
The way it's added doesn't work with modifiers like `md:break-words` but I hope we are not going to need that anyway. This applies mostly to mobile only anyway.
=> overwrite tailwind class to add chrome fix

src/components/TheSidebar.vue
On mobile the sidebar wasn't scrollable because the drag mechanic for sorting the spaces overrules it.
- use vuedraggable's [delay options](https://github.com/SortableJS/Vue.Draggable/issues/632)
- use `div @click` instead `router-link`, to supress long tab link context menu
- added `pointer-events-none` to avatar image, to supress long tab image context menu
=> fix mobile issues with draggable

src/App.vue
Fixes this layout issue:
- apply min-width of 0 to content container for overflows to work properly.
Read more: https://css-tricks.com/flexbox-truncated-text/
=> apply min-width to grow containers for overflows to work properly

src/components/Modal/Account.vue
Fixes:
This happens in browses that don't have Metamask installed.
If there wasn't any `injected`, it just went into the `v-else-if`.
=> dont show metamask on browsers that have not installed it

src/components/BaseBlock.vue, src/components/Block/Votes.vue, src/components/TheLayout.vue, src/components/TimelineProposal.vue, src/components/TimelineProposalPreview.vue, src/components/Ui/Markdown.vue, src/style.scss, src/views/SpaceProposal.vue, src/views/SpaceProposals.vue, src/views/Timeline.vue
Proposal page:
- put author/dropdowns in new line
- reduced text size/line height
- reduced paddings in votes block
Proposal list:
- reduced text size/line height
- reduced paddings
Timeline:
- removed borders
- (no other adjustments for now because I will try to merge those two components TimelineProposal.vue and TimelineProposalPreview.vue)
Looks good to me now all the way down to 360px width, which is still the most common according to [some statistic](https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide) I found.
Share/dropdown menus would look better if they were on the same line as proposal state and space but that's a bit tricky if author is meant to be in the middle on large screens. Some other day...
=> Mobile fixes

src/components/Block/Results.vue
I removed that timestamp var when I removed the block title. Then when adding back the title I forgot the timestamp.
=> added back timestamp for results block title

src/components/Modal/Confirm.vue
Fixes 0 VP issue after voting on cow space.
Simplest hot-fix is to just not refresh the proposal page after voting. It'll just show the "Your vote is in." confirmation message at the bottom.
Does that do the trick? Not sure if I understand the underlying issue and what's going on in the backend.
=> dont refresh proposal after voting on spaces in pending.json

src/plugins/safeSnap/Create.vue
Fixes safesnap form not showing when preview mode is enabled in first step when creating a proposal.
- hardcoded preview to false in safesnap's Create.vue
**Not to be merged yet. Wanna try some automation to create a PR to dev whenever we hotfix stable.**
=> Hotfix safeSnap create form

src/views/Setup.vue
If we show available ens addresses before spaces are loaded the `ownedEnsDomainsNoExistingSpace` will not work and all address that the wallet owns are shown. This also prevents the space setup flow from repeating.
=> Fix ens address showing before spaces are loaded

src/components/Modal/RevokeDelegate.vue
The new decentralized subgraph returns `null` instead of `''` for global delegations, causing `formatBytes32String` to fail.
It is passed either the space id or empty string now.
=> Fix revoking global delegation

src/components/Block/Results.vue
Fixes https://github.com/snapshot-labs/snapshot/issues/2147
Length for the symbol can vary a lot so the length check for choice string doesn't make sense under some circumstances. (This is just a quick fix)
=> Remove length check for showing tooltip

src/components/SetupProfile.vue, src/views/Setup.vue
Fixes https://discord.com/channels/707079246388133940/831512954435534898/963343919553327114
Steps to create space with not matching controller:
1. Connect with wallet that owns the ENS domain (Account 1)
2. Select the ENS domain on Setup page
3. Paste address (of Account 2) and sign tx to set the space controller 
4. On the `setup/profile` step switch to the controller wallet and create the space
- Prevent page from reloading on account change
- Fix admin not matching controller
=> Fix space creation with not matching controller

src/views/SpaceCreate.vue
Selectors for "voting type", "voting period" and "voting delay" didn't show the correct cursor on hover
- Show `cursor-not-allowed` when enforced by space
- Show `cursor-pointer` when not enforced
=> Fix create select button cursor

src/components/Block/Results.vue
Currently you can only see the results number in a compact format.
Changes:
- Show full number with rounded decimals in the results tooltip
=> Show full number in results tooltip

src/composables/useSpaces.ts
With this change instead of using space network to filter it use strategies network, which bring more interesting list example:
On https://snapshot.org/#/?network=100
On http://localhost:3000/#/?network=100
=> Filter by network using strategies networks

src/components/TheSidebar.vue
Fixes https://github.com/snapshot-labs/snapshot/issues/2581
- removed `draggableSpaces.value.some` because it didn't do anything
- switched ordering for new spaces (`-1` and `1`) so that they are at the top
=> Show newly followed spaces at top of sidebar

.github/workflows/update-snapshot-packages.yml
As we are using brovider now this will run every Monday, we can still trigger it manually anytime
=> Update snapshot packages only once a week than every hour

src/components/SpaceCreateVoting.vue
Blockfinder can only resolve a block based on a timestamp if that block is not the latest, this cause issue currently if you try to create a proposal on a space with multichain (you can try on fabien.eth), cuz Blockfinder wont find corresponding block based on timestamp unless the block is 2 block past already. This PR should fix it
=> Use earlier block to avoid bug with Blockfinder

src/composables/useStrategies.ts
Changes in this PR: Removes the "pagination" strategy from the list available strategies to select in the UI.
How to test and review this PR? Run snapshot locally, go to fabien.eth space, and try to change the space strategy to pagination. It should not appear.
=> 🗑️ Make pagination strategy not selectable in UI

src/components/ModalConfirm.vue, src/components/SpaceProposalVotesList.vue
Temporary fix for https://github.com/snapshot-labs/snapshot/issues/3228
This will hide the reason input inside the confirmation modal and also hide the reason icon on the vote if the proposal uses shutter.
We also need to make sure on the hub to not accept a reason for shutter proposals. @bonustrack
=> Hide vote reason input and display when shutter enabled

.github/PULL_REQUEST_TEMPLATE.md
**Background**
The current PR template starting with:
```
Fixes Issue #
```
doesn't automatically close the linked issue. This PR solves that, more info [in the Github docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
**Handling related PRs**
Sometimes there are several PRs that need to be merged together in an order: `A -> B -> C` where `C` is the final PR closing the issue. To avoid automatic closure through the partial PRs AB we can ask contributors to use the below for their descriptions:
```Fixes partially #``` 
which will not close the linked issue but will show up as a linked PR in the issue thread.
=> Fix PR template to allow automatic issue closure

src/composables/useWeb3.ts
Fixes #
N/A
The GameStop wallet currently cannot connect. When comparing the differences between GameStop and MetaMask on connecting, I found the problem is the GameStop wallet has no events to emit. When Snapshot then tries to subscribe to events, exceptions and thrown and this throws off the users ability to connect to the site. Adding a check for events in the condition check resolves this.
It seems chrome prompts for the 'Injected' option while Brave does not. This will only solve it for users in Chrome. Not sure how to get the 'Injected' option when connecting in Brave.
I connected to the dev instance without issue using the GameStop wallet. Then I went into the 'fabien.eth' space and cast a vote successfully. I also connected with …
=> Fix wallets connecting when they don't emit events

src/plugins/poap/index.ts
Hey! On this PR I've added the POAP API-Key. 
Starting on November 30th API-Key will be required in order to be able to use the POAP API.
From the POAP side, we now that adding and API-Key on a frontend application is not secure, at the moment it's just for identifying the traffic of our API.
=> Add POAP API API-Key

src/components/TextAutolinker.vue
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/521
Autolinker was missing `sanitizeHtml: true`
=> fix: Autolinker html sanitation 

.husky/pre-commit, src/components/MessageWarningGnosisNetwork.vue, src/components/ModalVote.vue, src/components/SpaceCreateWarnings.vue, src/composables/index.ts, src/composables/useClient.ts, src/composables/useGnosis.ts, src/locales/default.json, src/views/SpaceCreate.vue, src/views/SpaceSettings.vue
Fixes #3318
ℹ️  Also removed the pre-commit test because it's buggy and throwing an error in a file unrelated to the test
For settings it will check if the Gnosis safe network is set to the Snapshot `defaultNetwork`
For voting and proposal creation it will check if the network is set to the space network
=> fix: Show messages for gnosis safe on wrong network

src/components/BaseCalendar.vue, src/components/InputDate.vue, src/components/ModalSelectDate.vue, src/components/SpaceCreateVotingDateEnd.vue, src/components/SpaceCreateVotingDateStart.vue, src/style.scss
1. There was a bug with the button for going backwards in months, I couldn't find a fix so I made it always visible now.
2. Fix for light theme. The disabled (past days) were not distinguishable from enabled (current and futures days). And I also added a not allowed cursor for disabled days.
3. The current day is now indicated by a `primary` ring
4. The The currently selected date in now pre-selected when you open the calendar
Before             |  After
:-------------------------:|:-------------------------:
1. The time selector wasn't using the correct input so it was possible to enter invalid times. Fixed by using input with type `time`
2. The time input will now adjust to the browsers localization settings, f.e english is with `AM` `PM` and German is 24h
3. When clicking the clock …
=> fix: Improve date and time picker

src/components/SetupDomain.vue, src/composables/useEns.ts, src/locales/default.json
Fixes #2088
1. Shorten the displayed hash when `labelName` isn't available
2. Show a warning icon and tooltip with an explanation when `labelName` isn't available <img width="881" alt="image" src="https://user-images.githubusercontent.com/51686767/216083568-ea89b9f9-58e4-49dd-bde5-fafe66c2d9d3.png">
4. When user clicks the button with an invalid domain, it will open the ENS app in a new tab `https://app.ens.domains/address/<CONNECTED_ADDRESS>/controller` so that the user can further investigate the issue <img width="1421" alt="image" src="https://user-images.githubusercontent.com/51686767/216083404-2b01766c-7afb-4d9b-ba3d-fdf9d3313565.png">
1. Go to https://guest.on.fleek.co/#/0xa2e81c205e38324bf7432aecbd2c7e20c717e1d3 and connect to a deployment from this PR using WalletConnect
2. Go to …
=> Show warning for invalid ENS names on setup

src/components/LinkSpace.vue, src/components/ProposalsItem.vue, src/components/SettingsSubSpacesBlock.vue, src/components/SetupDomain.vue, src/components/SpaceProposalHeader.vue, src/components/SpaceProposalPage.vue, src/components/SpaceProposalsNoProposals.vue, src/components/SpaceSidebarSubspaces.vue, src/components/TheSidebar.vue, src/composables/useApp.ts, src/composables/useExtendedSpaces.ts, src/views/ProfileAbout.vue, src/views/SetupView.vue, src/views/SpaceProposal.vue, src/views/SpaceProposals.vue, src/views/SpaceView.vue, src/views/TimelineView.vue
Fixes #3455
- Show proposals from sub-spaces on custom domains
- Add checks to make sure that the proposal is related to the space using `isSpaceRelatedProposal`
- Fix links to sub-spaces on custom domains
- If sub-space also has a custom domain, then link to that
- If sub-space doesn't have a custom domain then link to snapshot.org
- Fix bugs and `extented` -> `extended` typo
1. Run deployment locally and add `"localhost": "SPACENAME.eth"` to domains.json inside `snapshot-spaces` sub-module.
=> fix: Show sub proposals on custom domain

src/components/ButtonPlayground.vue, src/components/ModalStrategy.vue, src/router.ts, src/views/PlaygroundView.vue
Fixes #3508
- Remove `playground` route for custom domain and redirect to `snapshot.org` instead
- Refactor all playground router.push logic into `ButtonPlayground.vue`
- Fix bug where example `addresses` wouldn't be filled
=> fix: Remove playground from custom domain

src/helpers/auth.ts, src/helpers/connectors.json
Fixes #
Added Kaikas wallet support to the connectors list. Kaikas is a global digital wallet functioning as a [web browser extension](https://chrome.google.com/webstore/detail/kaikas/jblndlipeogpafnldhgmapagcccfchpi?hl=en).
- Added kaikas wallet to connectors list
1. The "kaikas" wallet option should be shown when "connect wallet" is clicked.
2. User should be able to perform the snapshot operations with the connected wallet address from kaikas.
=> feat: Added Kaikas wallet support

src/views/SpaceProposals.vue
Closes: https://github.com/snapshot-labs/snapshot/issues/3564
As it was discussed here https://github.com/snapshot-labs/snapshot/pull/3543#discussion_r1125183478 but there was no "/" in a path to proposal from space without of custom domain.
Prop "to" in SpaceProposals => ProposalsItem
1. Go to space with custom domain and check proposal link
2. Go to space without custom domain and check proposal link
=> fix: proposal link in space without custom domain

src/App.vue, src/components/BaseSearch.vue, src/components/SpaceCreateContent.vue, src/components/SpaceCreateVoting.vue, src/composables/useFormSpaceProposal.ts, src/composables/useInfiniteLoader.ts, src/views/SpaceCreate.vue, src/views/SpaceProposals.vue
Fixes https://github.com/snapshot-labs/snapshot/issues/3664
1. Added key prop to SpaceProposalsMenuFilter
1. Go to space page and try to search
2. Click another space from sidebar
3. Search input should be reset
=> fix: reset proposal search input

src/main.ts
Fixes #3701 
1. Adds  `pilot.gnosisguild.org` to known hosts list
Visit snapshot.org with the Pilot extension, site should load.
More info about Pilot can be found here: https://pilot.gnosisguild.org/
=> add pilot extension to known hosts array

src/components/TheSidebar.vue
Prefer `<a>` instead of `<div>` with an onClick event, to not break keyboard navigation
Current link to spaces in the sidebar are created using a `<div>` + `onClick` event. These are not considered as native links by the browser, and are skipped when navigating the page using the keyboard.
Fix some part of #3707 
Use `<router-link>` to create link to spaces in the sidebar, instead of `<div>` + onClick event
Sidebar links should behave as before. They are just now focusable when using keyboard navigation
1. Open any page
2. Click on `TAB` key, and navigate through the sidebar
3. You should see that spaces link are now focusable
4. Focus any space, and click `ENTER`
5. You should navigate to the space page
I am not aware of why the div/onClick event choice has been made, over the …
=> fix: use <a> to create links to spaces in sidebar

src/components/ModalNotice.vue, src/locales/default.json, src/views/SpaceSettings.vue
Fixes https://github.com/snapshot-labs/snapshot/issues/3528
1. Added ModalNotice to SpaceSettings
2. Don't show again boolean saved to ls
1. Go to Space setting and save some changes
2. Notice modal will be opened, if you click "Don't show again" it will not be shown again after space settings saved.
=> feat: add settings saved notice

src/components/SpaceProposalVotesListItem.vue
When using the keyboard `ENTER` to trigger the vote receipt popover, it's crashing because it is unable to assign the IPFS hash url
Fixes #3714
Remove unneeded variable assignment on click event, just use the original variable
This function was probably inherited from another feature that does not exist anymore.
1. Go to https://snapshot-git-fix-3714-snapshot.vercel.app/#/aave.eth/proposal/0xea8b9cc41076ba43c8a66dfd40ce539b3126af049639babce6c1fa3e62585b79
2. Scroll down to the votes list
3. Press anywhere with your mouse just before the RECEIPT modal link 
4. Use the keyboard `TAB` to navigate to the icon opening the RECEIPT popover
5. Press `ENTER` to open the popover
6. popover should open without any errors, and IFPS link should be set
Nothing
There still a leftover useless variable, …
=> fix: fix keypress on button not triggering the ipfs hash fetching

src/components/TheNavbar.vue
Fixes https://github.com/snapshot-labs/snapshot/issues/3254
1. Made demo banner removable in TheNavbar.vue
1. Go to demo site and close the banner with "x"
2. Refresh the page the banner will appear again
=> feat: make demo banner removable

src/components/ProposalsItem.vue, src/components/ProposalsItemFooter.vue, src/composables/useIntl.ts, src/locales/ar-SA.json, src/locales/de-DE.json, src/locales/default.json, src/locales/es-ES.json, src/locales/fil-PH.json, src/locales/fr-FR.json, src/locales/hi-IN.json, src/locales/id-ID.json, src/locales/it-IT.json, src/locales/ja-JP.json, src/locales/ko-KR.json, src/locales/pt-PT.json, src/locales/ro-RO.json, src/locales/ru-RU.json, src/locales/tr-TR.json, src/locales/uk-UA.json, src/locales/vi-VN.json, src/locales/zh-CN.json
Add relative date for closed proposal in proposals list.
Relative date was already present for open and pending proposals, only missing for closed proposals.
Fixes #3426
1. Add relative date to end time, for closed proposals
2. Enhance UI of all proposals relative time
3. Add tooltip showing precise UTC time
1. Go to any proposals list (timeline or space)
2. Relative time should appear on the bottom, with a more consise time reference (end in, start in, ended x)
3. Hovering over the time should show a tooltip with the UTC time
Nothing
=> fix: add missing time reference to closed proposal

src/components/BaseProgressRadial.vue, src/components/SpaceProposalVotesList.vue, src/components/TheNavbar.vue, src/composables/useReportDownload.ts, src/helpers/queries.ts, src/helpers/snapshot.ts, src/locales/default.json, src/locales/fr-FR.json
When downloading the CSV files for a proposal votes, the file is capped at 6000 rows due to implementation of the new limit on the API side.
Fixes #1626
Implement the changes, as described in https://discord.com/channels/707079246388133940/1061540232769577061/1061540232769577061
1. the proposal query is now using the created_gte condition to get over the 6000 rows limit
2. the data in the CSV file is now ordered by created, instead of voting power
3. A progress icon is shown while the CSV file is being built
1. Go to a proposal with more than 6k votes (such as https://snapshot-git-fix-1626-snapshot.vercel.app/#/aave.eth/proposal/0xf6da417983653f7e7f5560a8e16ad77d5e25533bba9157abfd222347b40d09d0?app=senate)
4. Download all the votes as CSV file
5. A progress icon should be shown in lieu of …
=> fix: fix downloaded CSV votes file not containing all votes

src/components/BasePopover.vue
Temporary hotfix for page jump, on popover open, due to `focus: true`. Seems like a library issue, waiting for a fix on their side before reintroducing this.
Fixes #3743
1. Remove `focus` on popover, will lose some UX, but fix page jump
1. Click on any popover
2. Page should not scroll
focus will be reintroduced once the issue is fixed on the library side
=> fix: fix page jump to the top on popover open

package.json, yarn.lock
Since a few commits ago, lint task start running out of memory. 
From the internal discord discussion, seems like removing the lint task from the workflow has been decided as a fix, but the memory issue still exist when trying to run it, preventing running lint on local env. Even bumping my node dedicated memory from 2GB to 8GB does not resolve the issue, it's some kind of memory leak, and not just a not enough memory issue.
From my tests, after testing by reverting each commit, seems like the issue is coming from `prettier-plugin-tailwindcss` package, which is introducing ESM and TS config file support in 0.2.6.
1. Freeze `prettier-plugin-tailwindcss` to `0.2.5`
1. run yarn 
2. run yarn lint
3. linting should finish with success, and not out of memory error
=> chore: fix JS out of memory error when running lint

src/components/ProfileActivityListItem.vue
Add timestamp to profile activity
Fixes #3340 (partially)
1. Add relative time to profile activity
1. Go to a user profile
2. A relative time should appear for each activity
3. Hovering over the time should display a tooltip with the precise UTC time
=> feat: add timestamp to profile activity

src/composables/useProposalVotes.ts, src/helpers/snapshot.ts
1. Fix bug in `getProposalVotes` where `orderDirection` was `undefined`, this was related to how object destructuring works
1. https://snapshot-git-fix-votes-snapshot.vercel.app/#/arbitrumfoundation.eth/proposal/0x373dfa89fc9c5ccba8ed83fa3fa4f233edd270075b5f8f4f3902b408318d9d17
=> fix: Votes not descending

src/style.scss
Fix tooltip link color
Fixes #3742
1. Fix color property not applied to link
1. Go to a proposal list with vote
2. Hover the icon, the tooltip text should be same as if it was a text
=> hotfix: fix tooltip link color

src/components/BasePopover.vue
Resolving the issue from #3743 for good, where opening a popover make the page scroll back to the top. Hotfix was to disable the focus until the issue from the headlessui/float library was fixed
The library author has stated he won't fixed, but offer another method to implement the same result.
1. Add a FocusTrap element to handle the popover focus, instead of using the `focus` prop.
1. Opening any popover
2. The popover should open without scolling the page to the top
3. The next focus element should be something inside the popover
=> feat: restore focusable popover content on keyboard navigation

package.json, src/components/InputSelectVoteValidation.vue, src/components/ModalValidation.vue, src/components/ModalVoteValidation.vue, src/components/SettingsValidationBlock.vue, src/components/SettingsVotingBlock.vue, src/helpers/snapshot.ts, src/views/SpaceSettings.vue
Requires https://github.com/snapshot-labs/snapshot-strategies/pull/1113
Fixes https://github.com/snapshot-labs/snapshot/issues/3621
1. Add useVotingStrategies to the basic validation form allowing the user to switch between custom strategies and the default voting strategies of the space https://www.loom.com/share/4a53fd0c1b724dd39cff0584306b0e18
2. Add schema for form generation
=> fix: Add basic form schema and add useVotingStrategies property

.github/workflows/update-snapshot-packages.yml
This workflow is disabled right now,
If there are already 5 PRs from dependabot, it is hard to update snapshot.js
=> Disable schedule but keep manual dispatch for package update

src/plugins/safeSnap/constants.ts, src/plugins/safeSnap/utils/safe.ts, yarn.lock
Fixes https://github.com/snapshot-labs/snapshot/issues/3723
1. Use v2 URL for collectibles and v1 for others
2. Update yarn.lock
1. Go to https://snapshot.org/#/%F0%9F%8D%AFdao.eth/create/0 and go to transaction page
4. Open the networks tab to see the failing request for collectibles
=> Use v2 safe API URL for collectibles endpoint

src/components/ProposalsItem.vue, src/locales/default.json, src/views/SpaceProposals.vue
Fixes https://github.com/snapshot-labs/snapshot/issues/3777
1. Hide flagged proposals and only show when requested by user https://www.loom.com/share/0be8402003aa49fc9b89d319533a6eb0
1. gnosis.eth space
=> fix: Hide flagged title and description

src/components/BaseMarkdown.vue, src/components/ModalConfirmAction.vue, src/locales/default.json
Fixes part of Chaitus comment https://github.com/snapshot-labs/snapshot/pull/3791#issuecomment-1515800097
Loom: https://www.loom.com/share/61b44aa2107c4cb3a9bb956843687dc6
1. Show modal with real URL when clicking URL from proposal body
1. Proposal: `lido-snapshot.eth/proposal/0xd4e4bb2bb4bf725a3dc199d48b4442104b19768c22801dc192afb5001047c860`
=> feat: Add link preview modal

src/components/StrategiesListItem.vue
Open strategy page from strategy item.
Fixes https://github.com/snapshot-labs/snapshot/issues/3778
1. Added one more button to strategy item.
1. Go to '#/ens.eth/settings' and click on information icon
2. Test it with custom domain space
=> feat: strategy link

src/composables/useEns.ts, src/helpers/queries.ts
Resolve ENS domains and wrappedDomains, filter out reverse domains
Fixes https://github.com/snapshot-labs/snapshot/issues/3818
1. Extended ENS_DOMAINS_BY_ACCOUNT_QUERY
2. allDomains in useEns composable
1. Need account like @aurelianoB 0xa561e70cd46B6445D98Ffa26e0288C9E49C70B1a with wrapped domains
2. Go to create space and see wrapped domains and no reverse domains
=> feat: add wrappedDomains, filter out .addr.reverse

src/composables/useShortUrls.ts
This is a quick fix to avoid this:
=> fix: avoid github.com be detected as shortener provider

src/components/SettingsMembersBlock.vue
Lowercase addresses to check duplicates in space members.
Fixes https://github.com/snapshot-labs/snapshot/issues/3809
1. Added .toLowerCase() to address addressesArray/membersArray mapping.
1. Go to your space and try to add members with mixed case and the the same with lowercase.
=> feat: space members add with lowercase

src/components/BaseMessageBlock.vue, src/components/SpaceWarningFlagged.vue
Fixes https://github.com/snapshot-labs/snapshot/issues/3855
1. Fixes the issue above that stems from a recent update of Tailwind CSS that brought about changes to "specificity". Not exactly sure how and why.
1. Go to flagged space `zksyncvote.eth` and check for on sm and md screen sizes.
=> fix: Message block border responsive

src/plugins/safeSnap/components/HandleOutcomeUma.vue
Fixes #
When using osnap, after an execution of a vote, there is a time window where the proposal can be disputed. this updates the dispute link to the new oracle ui.  the code was already there, but link format is modified.
1. 
1.  on goerli, visit the outcome.eth space, propose a new approve vote, sending a small amount of eth from wallet with an expiry of 5 minutes.
2. vote affirmative, and wait till vote is over. see that you can execute the vote.
3. after execution see that theres a link to the oracle UI:
*_(Include any …
=> fix: Link to uma oracle url

src/plugins/safeSnap/components/Config.vue
There was a request to include ipfs link next to transaction viewer
This will render an ipfs link whenever it exists, next to the transaction title.
1. view any proposal with a transaction viewer, see the ipfs link exists, click it. 
=> feat: add ipfs link next to transaction viewer

src/helpers/snapshot.ts
There is a bug with the POAP plugin, when someone vote it's not detected and the button is greyed. You can check on this proposal: http://localhost:8080/#/rocketpool-dao.eth/proposal/0x19504a2bc3ac5b2b4fe9f54ef08ca23656fb4f6e678d17adb68c82d3bdf369af
by adding a valid voter address here <https://github.com/snapshot-labs/snapshot/blob/31411c83771b9ac4c4c2b3bf2c7bfbac76a9be43/src/plugins/poap/index.ts#L37> You'll see that the button stay grey, this is because the request we are sending to hub to check if someone voted is incorrect, we are sending `space = ''`. This PR fixes this
=> fix: mint button on POAP plugin

src/plugins/safeSnap/utils/events.ts, src/plugins/safeSnap/utils/umaModule.ts
After executing a proposal for Barnbridge, we are unable to determine the proposal was executed, which causes us to display a button to do this again. this will waste users funds if acted on. 
Fixes #
The bug was introduced as a side effect of fixing another bug. Previously we were getting block range limits when querying for events, due to having to look back to block 0. This was rectified by hardcoding a block range of 3k which seems to be the maximum block range for the specific provider we are bound to. This caused us to miss past events as we need to look back to block 4k+. 
1. The changes made are to respect the block range limit, while also "paging" through the broader range. We also limit lookback which was previously set to 0, to the start of the mainned OG and OO contract …
=> fix: page in events to fix lookback limitation

src/composables/useQuorum.ts
When `voting.hideAbstain` is set in the space settings we should not count Abstain votes towards the quorum.
1. Added a condition and filter to remove Abstain votes from Quorum score.
1. `testsnap.eth/proposal/0xad2c5d0d860c0a897e02893a723c2530e85badaf0a055a1efad4ffc7e811ecd3`
=> fix: Remove abstain votes from the basic voting quorum score

src/plugins/safeSnap/utils/events.ts, src/plugins/safeSnap/utils/umaModule.ts
A side effect of paging in all past events, is that loading is really slow. This is due to loading them in a blocking way, it can take almost a minute to complete loading of all events. 
Fixes #
1. This parallelizes calls in 2 main places. First is where we paginate the events, we now create a list of start/end blocks, and then call them all in parallel, previously this was done sequentially.
2. For all event types in the uma module, previously they were called one at a time, now we call them all together.
This seems to have sped up loading significantly, and have not seen any rate limit errors. All events load in around 5 seconds.
1. Visit the barnbridge …
=> improve: parallelize event loading

src/plugins/safeSnap/utils/index.ts, src/plugins/safeSnap/utils/umaModule.ts
There is a problem showing the execution date of proposals in liveness, errors are being showin in console. 
Fixes #
The bug was caused by replacing 0x in incorrect places in ancillary data, causing a slight mismatch when searching for events relevant to proposal. this would create an impossible state, and undefined values further down the code. 
1. We change to use a regex to only replace 0x in the front of hex strings before doing comparisons.
1. visit https://snapshot.org/#/acrossprotocol.eth/proposal/0x58069d8f80093bea2a91955dcd871a6f0f321005dd9e9ca9756ef98d416b3fd1 and see no execution time show for this proposal, errors show in console
2. visit the same proposal in the preview link, see that it shows a …
=> fix: fix incorrect hex 0x replacements

src/components/BasePopover.vue, src/components/SpaceProposalVotesList.vue
Fixes #3940
1. UI: Add a focus trap to popover, so on open, the focus is on a hidden element, instead of the first clickable element. 
2. UX: Fix "See more" button, for opening the votes modal, not actionable by keyboard navigation.
1. Use `TAB` key to navigate to header notification menu.
2. Open the menu
3. Nothing should be focused
4. Press `TAB`
5. The first element should be focused
1. Go to a closed proposal with votes
2. Scroll down to the votes list
3. Use the `TAB` key to navigate and focus the "See more" link
4. Press ENTER
5. The votes modal should open
=> Fix popover missing focus trap

src/components/SpaceProposalVotesListItem.vue
Votes reason with trailing and leading line breaks are shown as is in the tooltip.
Part of #3944
1. Trim leading and trailing line break from the reason
1. Go to https://snapshot-git-fix-3944-snapshot.vercel.app/#/opcollective.eth/proposal/0x88583c43b196ec86cee45345611b582108f1d6933ab688a7cae992a6baa552a6
2. Open the votes list modal
3. Filter with the following address: `0xe43C840612d5672920FC33ACc55390357D9EcE3d`
4. The reason should shown without leading line break
=> fix: remove trailing and leading spaces and line break  from reason

package.json, patches/readable-stream+3.6.0.patch, yarn.lock
#3961 
Fixes #
patch `readable-stream` dependency. The problem was with the wrong resolving of dependencies.
1. Login with a Coibase wallet
2. Try to vote
=> fix(voting): fix voting with coinbase

src/components/SpaceCreateContent.vue, src/components/SpaceCreateVoting.vue, src/views/SpaceCreate.vue
Its been suggested that we restrict voting type to "basic" when doing an osnap vote. This is because osnap team does not have the ability to automatically monitor and dispute arbitrary vote types where user may define other fields. Restricting this will allow more robust on chain monitoring and disputing of bad proposals.
Fixes #
1. we add code to check if the user has a valid osnap install
2. if they do, during proposal building, we add a selection where the user can specify if they want to use osnap 
3. if they choose yes, we hard code the vote type to basic, and prevent user from selecting anything else
this only shows if osnap is enabled and working:
1. go to /#/outcomefinance.eth/create, which should be an osnap space
2. begin the proposal process, see that you are asked if you want …
=> feat: enable osnap selection to restrict voting types

src/helpers/connectors.json
Fixes #
1. Problem with connection using Rainbow Wallet
1. Moved `eth_accounts` to optional methods
1. You need to try to login using Rainbow Wallet and WalletConnect v2
=> fix(walletconnect): changed wc config

package.json, src/composables/useGnosis.ts
Fixes #
Add the ability to detect gnosis-safe wallets if the web3 provider doesn't contain any information
1. Add an extra check whether the address code is equal to `0x`. If not equal then the address belongs to a contract. 
1. Login with gnosis safe
2. Check that you are not able to join any space
=> fix(gnosis safe): add extra check for gnosis contracts

src/components/SpaceProposalResultsList.vue
This was causing confusion as the proposal doesn't use a quorum but uses space settings to display it.
Fixes #
Instead of displaying the quorum from space settings, utilize the proposal quorum.
Before: https://vote.gro.xyz/#/proposal/0x7e6a526031028514cf78fb8618a65d1cc71d457549f8c1b8180a96443d741428
After: https://snapshot-git-fix-quorum-with-space-settings-snapshot.vercel.app/#/gro.xyz/proposal/0x7e6a526031028514cf78fb8618a65d1cc71d457549f8c1b8180a96443d741428
Before it was displaying quorum section, now it should not
=> Do not display quorum from space settings, use proposal quorum

src/components/ProposalsItemFooter.vue
Quorum % in proposal item footer is failing when percentage number is too big, due to number formatting converting it to something like "277K" first
Fixes #
1. Remove the number compact formatting
- Visit https://snapshot-git-fix-nan-quorum-snapshot.vercel.app/#/grants.safe.eth
- Quorum percentage should not show `NaN` anymore
=> fix: fix failing percentage formatting for big number

src/plugins/safeSnap/components/HandleOutcomeUma.vue, src/plugins/safeSnap/utils/umaModule.ts
Some testing has revealed that we have not been able to execute proposals once they passed voting period.  This is a very high priority problem. 
Fixes #
1. There were some logical bugs when calculating proposal button state
2. we were using assertionid on some event queries where assertionid was 0x0
1. go to frp.eth/proposal/0x405b90d914c3499ec4610db918a1692eb1e9edc42006216e66cc2721edeb059f
2. see that there is an executable proposal
3. go to barnbridge.eth/proposal/0x74cf6f3372aaeebfc2e99ff54604a5e63ca3d44cb84bdbf202a85581dfac9f5d
4. see that the proposal has been executed
*_(List any outstanding …
=> fix: fix inability to submit proposals

src/views/SpaceCreate.vue
[Discord](https://discord.com/channels/955773041898573854/1030772384308932608/1125979225078370385)
Fixes #
Remove the restriction of the start time for Safe wallets
1. add a check of Safe to the `SpaceCreate` view. If it's Safe, then the start time will not be restricted to be greater than now.
1. Try to create a proposal with the Safe wallet.
=> fix(start): remove start time restriction for Safe

src/views/ProfileActivity.vue
[Discord](https://discord.com/channels/955773041898573854/1030772384308932608/1126143002285453413)
Fixes #
1. add a check that prevents loading activities if the list is empty. In other words - there is nothing to load and the infinite scroll triggers continuously
1. Go to profile activities and check that you don't have duplicates
=> fix(activities): prevent loading activities for empty list

src/plugins/safeSnap/components/Form/TokensModal.vue, src/plugins/safeSnap/components/Form/TokensModalItem.vue, src/plugins/safeSnap/components/Form/TransferFunds.vue
Fixes #4026 
1. Use the network from the safe config to generate the explorer urls for tokens
1. https://snapshot-git-samuv-fix-token-explore-snapshot.vercel.app/#/outcomefinance.eth
=> fix: Use config network for tokens explore url

src/plugins/safeSnap/constants.ts
fix #4062
---
I have checked everything, it's just fixing the endpoint. That value is ONLY used for ABI fetching, in safeSnap/utils/abi.ts
=> fix: blockscout new api url

src/components/ModalNotice.vue, src/components/ModalSelectDate.vue, src/components/ModalTerms.vue, src/components/ModalVote.vue
There's a few button with `type="submit"`
Unless the submit button is inside a `<form>` tag, it's basically useless, and just a regular `button`
1. Remove all `type="submit"` property for button not inside a `<form>` tag
1. 
=> chore(refactor): remove useless submit property

src/plugins/safeSnap/components/HandleOutcomeUma.vue
currently the oSnap UI does not check if a vote has passed quorum, or even if majority voted "for" the proposal before allowing a request for execution. we want to prevent requesting execution of osnap votes unless they first pass snapshot rules.
Fixes #
1. adds a utility function that looks at the proposal state, and does some basic checks for votes against quorum and that "for" is more than "against". 
1. we can check #/frp.eth/proposal/0x3d12840b17a64af60fb75c7dae17846f64836b702eab3c9ae178debe40a4af6c and now see that if a proposal is voted down, it shows "proposal rejected":
2. it continues to show proper states ( no regressions ) for the rest of passed …
=> feat: check if vote passes before allowing execution

src/plugins/poap/components/CustomBlock.vue
Fixes https://github.com/snapshot-labs/pitches/issues/14
1. Hides the poap block if Poap is not setup for the proposal
2. There is no way to hide the 404 error message, so i am gonna ignore it for now
- POAP block should not show up here https://snapshot-git-hide-poap-if-no-poap-snapshot.vercel.app/#/stgdao.eth/proposal/0x108a9e597560c4f249cd8be23acd409059fcd17bb2290d69a550ac2232676e7d
- POAP block should show up here 
https://snapshot-git-hide-poap-if-no-poap-snapshot.vercel.app/#/fractiontoken.eth/proposal/0xeaaf4b685084762f952f587fc8aa0725b40bc4c2d77e4e976a4125d3621cf7c3
=> fix: Hide poap block if there is no POAP is setup

src/components/SpaceCreateVoting.vue
In order for oSnap to work properly, the space needs to be able to create proposals with basic voting. If a space disallows this through space settings, then we must let them know. Currently this situation is not checked, and allows the user to go through 
the proposal process, only to fail in the end. 
1. this adds logic to notify the user that the spaces settings are incompatible with osnap, and directs them to the settings they must change to enable it. it will also disallow user from using osnap.
1.  visit a space a space with osnap and basic voting dissallowed, like #/umadev.eth/create
2. create a proposal, and see osnap disabled, with text explaning why …
=> fix: disable osnap if basic voting is not allowed and inform

vercel.json
#102 
Fixes #
add redirect to `/`
add vercel.json config file
1. Open some not existing pages, e.g. `https://snapshot.org/sialala` (use your own domain)
2. Vercel shouldn't show 404 and just show a dashboard (unfortunately the link will be `https://snapshot.org/sialala/#/`
=> fix(404): redirect to dashboard page

src/components/TheFlashNotification.vue
Toast was getting messed up when error was too long.
Before: 
After:
=> fix: Clamp error in flash notification

src/style.scss
=> fix: Change dark bg and reduce shadow

src/components/MenuAccount.vue
Change label from `Email subscriptions` to `Email notifications` in account menu
=> fix: fix email notifications label in menu account

src/plugins/safeSnap/constants.ts, src/plugins/safeSnap/utils/umaModule.ts
There were a few bugs discovered when we made breaking changes to our OG subgraph. This error caused us to fallback to web3 calls, which then also failed for some chains, discovered on gnosis chain.
1. if contract start blocks were not defined, this would cause an error with paging in events
2. once that was fixed, the block range for gnosis chain was too long (10000) so now its reduced to 3000 for all chains
This primarily fixes the broken subgraph call, secondarily fixes some of the web3 fallback logic when paging in events.
1. visit https://snapshot.org/#/umadev.eth/proposal/0xdf579f44cdc6a956720f260778939b178b654069ae3262fbe03eca9c710f3df9
and see that theres an error loading the proposal button
2. visit …
=> fix: fix broken gql call, narrow block query range

.github/workflows/codeql.yml, .github/workflows/deploy.yml, src/components/BasePluginItem.vue, src/plugins/commentBox/plugin.json, src/plugins/hal/plugin.json, src/plugins/poap/plugin.json, src/plugins/projectGalaxy/plugin.json, src/plugins/quorum/plugin.json
Recently we renamed our default branch from develop to master, so better if we change the code references
=> fix: Rename develop to master branch

package.json, src/composables/useImageUpload.ts, yarn.lock
Pineapple.js library throw an error on network error, and return a Promise rejection on pineapple server error. This duplicate the error handling process.
1. Upgrade pineapple.js to v1, which now return a Promise rejection following the same format for pineapple server error, as well as network error. This introduce no new features, just  remove the duplicate error handling.
1. Upload an image invalid image
2. It should show an error (from pineapple)
3. Switch off internet, and upload an image
4. It should show an error (network error)
5. Set the pineapple backend url to a 404 url
6. It should show a "Not Found" error message
Both errors should appear in the same format
=> fix: upgrade to pineapple@1

package.json
Fixes https://discord.com/channels/955773041898573854/1030772384308932608/1159426982942093353
1. Update Tune with fixed Listbox dropdown
1. Go to strategies and add `aave-governance-power` strategy
2. Click `Add` without filling out any fields
3. See error message
=> fix: Strategy form Listbox not showing error

src/views/PlaygroundView.vue
The playground error message readability can be improved. It currently looks like:
Most of the error messages will come in a JSON-RPC format (default error response returned by the snapshot.js SDK), we should pretty print the JSON like
1. Go to the playground
2. Trigger any scenario with error messages (test this one: https://snapshot-git-improve-playground-error-ui-snapshot.vercel.app/#/playground/erc20-balance-of?query=eyJwYXJhbXMiOnsic3ltYm9sIjoiQlJQIiwiYWRkcmVzcyI6IjB4QUI3ODExODhkNEY0MWYzNmVmRmY1MDc3OERDODczZjY4Rjk3ZTkzOSIsImRlY2ltYWxzIjo0fSwibmV0d29yayI6IjgwMDAxIiwic25hcHNob3QiOiIifQ..)
3. The error messages should shown pretty printed
=> fix(ui): improve playground error message readability

src/helpers/queries.ts
Fixes https://discord.com/channels/955773041898573854/1037286915549958164/1162138062223061055
Before we were loading only the last 20 votes of the user, in this PR we increase it to 1000.
1. Go to a space where you have voted on many proposal over the past weeks, see if the voted indicator appears on all the proposal as you scroll down
=> fix: Increase votes loaded to fix voted indicator not showing

src/components/BaseMarkdown.vue, src/components/SpaceProposalVotesListItem.vue, src/components/TextAutolinker.vue, src/helpers/utils.ts
Fixes https://discord.com/channels/955773041898573854/1031838169282392144/1162028062846746666
1. Instead of disabling HTML in the reason tooltip, we use TextAutolinker component which sensitizes the HTML and prevents attacks.
2. Added link preview to TextAutolinker so when the link is clicked it will also show a modal with the real link before opening, this prevents hiding malicious links inside the HTML.
1. Go to `testsnap.eth/proposal/0xcc3b8b204d80e86a95248e23bfa674ebbbe4315875a35f91892f2c96089b0a51`
=> fix: Clickable reasons links and link previews

src/composables/useFollowSpace.ts
Right now we are not displaying any errors if `follow` action return any error, this is effecting a case while user trying to follow more spaces than the limit
1. Go to the home page
2. follow 26 spaces
3. you should see the error like below now
Or 
1. Go to the home page 
2. Disable network
3. Try following a space
5. you should see an error now
=> fix: Show error if user reach follow limit

src/composables/useQuorum.ts
Right now:
Two possibilities when we display quorum on UI:
- `proposal.quorum`
- `space.plugins.quorum`
But there are three possibilities to calculate quorum (order of priority)
1. `proposal.quorum`
2. `space.voting.quorum`
3. `space.plugins.quorum`
So removing the `space.voting.quorum` will solve our problems 
1. Update your space settings to have only `space.plugins.quorum`
2. Create a new proposal
3. Notice that the quorum section displays a value from `space.plugins.quorum`
4. Update space settings with `space.voting.quorum` 
5. Create a new proposal
6. Notice that the new proposal will calculate quorum with `proposal.quorum`
7. Now go back to the previous proposal we created
-  Notice that it uses `space.voting.quorum` instead of `space.plugins.quorum`
- With this fix, it will use …
=> fix: Don't use space level voting.quorum

src/components/ButtonFollow.vue, src/composables/useFollowSpace.ts
We are not loading follows on custom domain, so user are not able to see if they already follow a space or not
Closes: #4317 
1. Checkout this branch in local
2. Add this to domains.json `"localhost": "zkswapfinance.eth"`
3. Click on "Join" button and reload, before fix you should see the "Join" button again after fix you should see the "Joined" button
=> fix: Load follows on custom domain

src/components/NavbarAccount.vue
- With `watchEffect`: `loadProfiles` is being called multiple times (when the component is created and when `web3Account.value` is updated)
- With `watch`: `loadProfiles` will be called only when `web3Account.value` is updated
How to test:
- Go to snapshot.org
- Login with any wallet
- Notice the difference in number of network calls to brovider
Or in local add a comment in `loadProfiles` to see how many times it is being called
=> fix: loadProfiles is called multiple times

src/components/SpaceCreateVoting.vue, src/components/SpaceCreateVotingDateEnd.vue, src/components/SpaceCreateVotingDateStart.vue
Date modal opens even if the space has a fixed voting delay and period, refer to the screen below
Date buttons should be disabled and should not be clickable
`SpaceCreateVotingDateEnd` and `SpaceCreateVotingDateStart` component is wrongly inheriting `disabled` property from the `SpaceCreateVoting` 
1. Add voting delay and voting period on your space
2. Try creating a proposal
3. should see the date fields to be disabled and non-clickable
4. Also try editing the proposal, here date fields should be disabled irrespective of the voting period and delay
=> fix: disabled prop for voting date inputs

src/views/SpaceSettings.vue
When navigating the space settings page, and leaving after browsing the different tab (strategies, delegation, etc...), it sometimes open a confirmation modal dialog, asking to confirm if we want to leave, due to unsaved changes.
This confirmation modal should be presented only to users with write permission (space controller and admins), and is irrelevant to other users.
1. Go to a space settings page you don't have permissions, e.g https://snapshot-git-skip-save-modal-when-no-permission-snapshot.vercel.app/#/stgdao.eth/settings
2. Go to delegation tab
3. input something in the inputs
4. Click on some link to leave the space settings
5. before fix, it should open the confirm dialog, after fix, it just leave.
6. Repeat the same on a space you have admin permission
7. on leave, it should …
=> fix: skip the confirm save modal when the user do not have permission

src/components/ModalValidation.vue, src/components/SettingsStrategiesBlock.vue, src/components/SettingsValidationBlock.vue, src/components/SetupExtras.vue, src/components/SetupStrategyAdvanced.vue, src/composables/useFormSpaceSettings.ts, src/locales/default.json, src/views/SetupView.vue, src/views/SpaceSettings.vue
Add proposal validation field to space setup and set validation.
On space creation and settings page we need to show errors for the recently enforced proposal validation rules. Errors also only show now after clicking "Save" or "Create".
Space setup:
Space settings:
1. Select "Anyone can create" on setup and settings page. See error
=> fix: Show validation errors for proposal validation

.env, README.md, src/helpers/clientEIP712.ts
=> fix: Change testnet URL

src/components/AvatarSpace.vue, src/helpers/queries.ts
You will see different image if you go to:
- https://snapshot.org/#/wen%F0%9F%8C%95.eth 
- https://snapshot.org/#/?q=volta+club+
This is because of a Stamp issue https://github.com/snapshot-labs/stamp/issues/119 - Not sure about the reason yet,
But the explore page is not using this cache because it is not querying the `avatar` param, It should be using the cached one like everywhere else
- Go to https://snapshot.org/#/?q=volta+club+
- Notice that space image will not contain a `cb` query, for example: https://cdn.stamp.fyi/space/stgdao.eth?s=164
- Go to https://snapshot-git-fix-avatar-issues-snapshot.vercel.app/#/
- Space Image will contain a query param `cb` like https://cdn.stamp.fyi/space/stgdao.eth?s=164&cb=7faee6797e3d57e7
=> fix: Explore page is not using cached image

src/composables/useProfiles.ts, src/helpers/utils.ts
Fix profile page such as https://snapshot.org/#/profile/0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3 where the `useProfile` does not have the current profile address, thus the missing profile details.
This was due to stamp API not returning addresses without any associated domains.
After fix, profile should work https://snapshot-git-fix-profile-loading-snapshot.vercel.app/#/profile/0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3
=> fix: fix missing keys in profiles

src/helpers/utils.ts
Stamp API only accepts 250 addresses maximum. 
This PR cap the max addresses sent to stamp to 250 addresses
=> fix: limit number of addresses sent to API

src/components/SetupExtras.vue
While creating a space, "Proposal validation" is shown under  "Members"
But on safe it is entirely different as shown in screenshot 🤔  this is preventing Safes from creating spaces
This is because we have different space creation flow for safe 
Easiest way to test this is: Replace these https://github.com/snapshot-labs/snapshot/blob/fix-validation-block-errors/src/composables/useGnosis.ts#L46-L50 with `true`
This will make your wallet look like a safe wallet
- Try creating a space, at the end click the "Create" button without adding proposal validation
- without fix: clicking on "create" will not do anything
- with fix: click on "Create" will show an error on the proposal validation block
=> fix: Proposal validation error is not shown to Safe space creators

src/helpers/utils.ts
Following https://github.com/snapshot-labs/stamp/pull/134
Decrease the max number of addresses sent to stamp `lookupAddresses` endpoint
=> fix: decrease max number of addresses

src/composables/useProposalVotes.ts
When scrolling down fast in the votes modal the stamp query for the ens names would pile up. Resulting in to large queries for ens and lense resolver.
=> fix: Stamp query in votes modal

src/views/SpaceSettings.vue
Users are getting the following error while deleting a space
This is because we assume `payload` param to be a object and not null in `useClient.ts`
- Go to space settings
- Go to `Advanced` -> Click on delete space -> Enter your space name name to confirm
- Before fix: you should see the error
- After fix: you should see the sign modal open (don't click on "sign" :D it is hard to recover your space)
Originally reported here https://discord.com/channels/707079246388133940/1178307743833133086/1178313172722126899
=> fix: Space deletion not working

src/components/SpaceCreateWarnings.vue, src/views/SpaceCreate.vue
Add check on proposal creation if space settings are valid and show message how to fix it
1. Go to `testsnap.eth/create`
2. See message
=> fix: Validate space settings on proposal creation

src/composables/useProposals.ts
Whenever we go to any [proposals page](https://snapshot.org/#/stgdao.eth) Notice that we are sending two queries to `votes` 
this is because `getUserVotedProposalIds` is being called twice, once when proposals are loaded and once when the user account is changed, and here both are loaded at the same time so one request has empty array `[]`
Due to this, You may also notice this error 
But it is related to https://github.com/snapshot-labs/snapshot-hub/issues/760
=> fix: Don't run votes query for default value

src/components/SettingsVotingBlock.vue
The placeholder on space settings (read-only mode) is confusing, It looks it got 1000 quorum 
Got to any space settings https://snapshot.org/#/stgdao.eth/settings got to voting -> quorum 
Before:
After:
=> fix: quorum placeholder in read-only mode is confusing

src/composables/useEns.ts, src/helpers/queries.ts
Right now we show expired domains while space creation, it is confusing
- Go to https://snapshot.org/#/setup?step=1 
- Login with https://guest.on.fleek.co/#/0x9c3aC02Cd616a82C83830e40D45c9534b32c4934
- You will see expired domains before fix
=> fix: Ignore expired ENS domains on space creation

src/App.vue, src/components/NavbarAccount.vue
With custom domains `loadProfiles` is not being called on the initial load, but without a custom domain `web3Account` is being updated 
Closes https://github.com/snapshot-labs/snapshot/issues/4352
=> fix: Profiles not loading with custom domain

src/components/TheNavbar.vue
I've removed the demo banner, it's too much highlighted, we have some users who use demo. to do production vote on testnet. I changed to a simple "testnet" label next to logo:
=> chore: replace demo banner with testnet tag

src/assets/css/tune.scss, src/components/SpaceProposalVote.vue
It might not be clear to the user that ranked choice voting requires all choices to be selected. To fix this I've added a tooltip to the disabled button.
Also added one for other voting types while at it
Also changes the disabled style of the primary button to fix the design on figma
=> fix: Add tooltip to vote button

src/composables/useEns.ts
Subdomains are not visible sometimes, because someone them has `0` expiry 
for example https://app.ens.domains/two.serebryakovpavel.eth in such cases we should check the parent's expiry but this is a temporary fix to show subdomains for space creation
1. Connect wallet with `0x2A54FbCb3e916Bb07F25c50093b9290173ef5248` using guest
2. Go to https://snapshot.org/#/setup?step=1
3. Before fix you should see only one domain
4. After fix you should see two domains
=> fix: Subdomains expiry is '0' sometimes

src/sentry.ts
Stop saving session sample on Sentry, because of quota usage
=> chore: stop logging session sample rate

src/plugins/oSnap/plugin.json
We recently added a new osnap plugin to snapshot, but forgot to update the manifest with website link and correct icon
Currently we use the safesnap plugin, which is not correctl
This is the new icon 
Closes: #
1. go into a space you can edit
2. add the new osnap plugin, see the new icon
=> fix: fix osnap site and icon links in manifest

src/components/SpaceCreateOsnap.vue
We had feedback around the wording of oSnap vs SafeSnap
Original wording:
>    The new oSnap plugin is not compatible with the legacy safeSnap plugin.
Please remove the safeSnap plugin in your space settings to enable
oSnap.
new wording
Closes: #
1. Add both oSnap and SafeSnap plugins to a space you control
2. You may need to configure the safesnap plugin wiht a valid module addresrs. Or use our test space umadev.eth
3. make a proposal, and go to the second page where this warning shows.
4. see that it doesnt show when only 1 of the plugins are installed ( should only show when both are installed )
=> improve: adjust wording about osnap vs safesnap plugins

package.json, src/helpers/validation.ts, yarn.lock
This is blocking https://github.com/snapshot-labs/snapshot/issues/4488
Every time there is some change in snapshot.js ajv (if we want to add a new format or new keyword) we have to redo it here in UI again, this PR will use snapshot.js 's ajv 
1. Go to settings form or proposal creation form and try different inputs, those should still show error same as before
=> Use AJV from snapshot.js

src/components/ModalVote.vue, src/components/SpaceProposalPage.vue, src/components/SpaceProposalVote.vue, src/components/SpaceProposalVoteApproval.vue, src/components/SpaceProposalVoteQuadratic.vue, src/components/SpaceProposalVoteRankedChoice.vue, src/components/SpaceProposalVoteSingleChoice.vue, src/components/SpaceProposalVotesList.vue, src/components/SpaceProposalVotesModal.vue, src/composables/useProposalVotes.ts, src/views/SpaceProposal.vue
When a user has already voted we show the selected choices and hide the other ones. We also add a "Change vote" button for the user to change their vote. When shutter privacy in enabled we show a message.
Use `pistachiodao.eth` space which has proposals for all voting types
=> feat: Show user vote in vote section 

src/components/SettingsStrategiesBlock.vue
Reported here https://discord.com/channels/955773041898573854/1182427601046884352/1195408731689734334
Strategies in settings is not working due to wrong path given in PR #4495 
- Go to any space's settings -> strategies
- Before fix it should break the page
=> Fix: Wrong schema path

src/components/SpaceProposalVotesListItem.vue
Clocking on a vote's reason icon should trigger the tooltip, additionally to just hovering over it.
This also fix the issue with keyboard navigation where the tooltip previously does not show when just focused. With this PR, we can click ENTER or SPACEBAR after focusing on the reason icon, to show the tooltip.
Closes: #4426
1. Go to a votes list with reason
2. Click on the reason icon
3. It should toggle the tooltip
4. Hover on a reason icon
5. It should also trigger the tooltip
6. Use keyboard to navigate and focus on a reason icon
7. Clicking SPACEBAR or ENTER should show the tooltip
=> fix: trigger vote's reason tooltip on click

src/components/SpaceCreateContent.vue
On proposal creation page, the error container error is show even though it is empty, when focusing on the proposal body textarea.
As the error container has a margin top of 2px, it shift all content below slightly, see video
https://www.loom.com/share/fd6a24b49e6a414ebf13f30a912472c5?sid=35d0ef71-a6f3-4698-ab90-0c54ae69fc4b
This PR will show the error container only if does contain an error
1. Go to the proposal creation page
2. Before, focusing the textarea will shift the discussion form by 2px
3. After, no more shifting
=> fix(ui): do not show empty error container

src/components/MenuAccount.vue, src/components/ModalEmail.vue, src/components/ModalEmailManagement.vue, src/components/ModalEmailResend.vue, src/components/ModalEmailSubscription.vue, src/components/ModalPostVote.vue, src/components/SpaceProposalPage.vue, src/composables/useEmailSubscription.ts, src/composables/useModal.ts
A request is sent to the envelop API on page load, to retrieve whether the current user is already subscribed or not. This was made so that when the user click on the "Email subscription" menu, it open the correct modal.
This PR introduces a change, to defer this request to only triggered when the user click on the "Email subscription" menu, thus saving a request on each page load, for user not interested in the email subscription.
This change introduces a change on the UI:
- Since we don't know the user subscription state when he open "Email subscription" modal, a loading skeleton will be show until we get the state from envelop API, before showing the correct modal content.
- In the PostVoteModal, we will charge the user subscription status on mounting, so there will be a UI flash, …
=> fix: defer email subscription state fetching

src/components/TheNavbar.vue
Closes: #4427
1. Go to a custom domain
2. The hambuger menu should not appear anymore
=> fix: hide hamburger menu on custom domain

src/components/SpaceCreateOsnap.vue, src/plugins/oSnap/components/HandleOutcome/HandleOutcome.vue, src/plugins/oSnap/utils/getters.ts
We had a bug report when using osnap and approving a bond, the approval button would not change to reflect the state of approvals on the user account, preventing them from executing the proposal. 
Secondarily we wanted to update wording around an unrelated warning when both osnap plugin and safe snap plugins are installed.
1.  in the staging link go to this proposal: #/the-co-dao.eth/proposal/0xd6ca97171b16f6927d2d196d01bbceb69db999d808430edc5b9662052e9c9527
2. make sure you have enough eth for bond
3.  see that theres a button to approve bond. if not you may need to revoke 
4. once bond is approved, see that the buton changes to allow execution ( previously this would not change) 
Also for the wording of warning:
1. go to uma space and create a proposal
2. on second page, see that the …
=> fix: approval loading after approve and some wording

src/locales/default.json, src/views/SpaceSettings.vue
Add additional checkbox on delete space modal, to make user confirm that it's impossible to re-create a space with the same name.
The goal will be to raise user awareness in case he misses the first and second warning message, as ticking a checkbox is get more attention
Closes: #4513 
1. Go to one of your space settings, then advanced tab
2. Click on "Delete space" button
3. It should show a modal with an input and checkbox
4. Fill the input with space name
5. Tick the checkbox
6. Click on delete space 
The "Confirm" button is enable only when both form element are valid
=> feat: add new checkbox to confirm inability to recreate space with same name

src/plugins/oSnap/Create.vue, src/plugins/oSnap/Proposal.vue, src/plugins/oSnap/components/TransactionBuilder/ContractInteraction.vue, src/plugins/oSnap/components/TransactionBuilder/Transaction.vue
Theres an issue when selecting a custom contract to create a proposal.  Its not correctly saving the state once the propsal is published.
Closes: #
1. make sure you have a space you can test with osnap plugin
2. create a proposal, do a custom contract, use an erc20 or some abi like this
3. choose function, set parameters
4. publish proposal
5. see that the parameters all look correct and match proposal
=> fix: fix custom contract proposal creation and view

src/components/BaseModalSelectItem.vue, src/components/ModalVotingPrivacy.vue
Disable voting privacy (shutter) on testnet
Closes: #4517 
1. Go to your space settings on testnet
2. Go to votes
3. Click on privacy input
4. All options beside "All" should be disabled
When doing the same steps on mainnet, you should be able to select "Shutter"
=> fix: disabled space votes privacy on testnet

src/plugins/oSnap/Proposal.vue
When creating a raw tx, the data field would not show in the proposal page
Closes: #
1. Using an osnap space, create a new proposal
2. select raw tx
3. enter value in the data field
4. propose, and ensure the transaction shows a data field in vote page
=> fix: show data for raw tx

src/helpers/validation.ts
Do not force form error message to be lowercase (beside first char). 
Some error message are case sensitive, like regex 
Closes: #4512
1.
=> fix: do not force error message casing

src/components/SpaceCreateLegacyOsnap.vue, src/components/SpaceCreateOsnap.vue, src/plugins/oSnap/Create.vue, src/views/SpaceCreate.vue
We had a bug where you could not progress on creating a safesnap tx using osnap, and then we would show a big warning that shouldnt have been there on the tx page. Fixing this uncovered other issues with warnings and incorrect wording, as well as cases where safesnap is configured incorrectly. 
we now have several screens depending on your configuration:
safe snap configured incorrectly for osnap, and osnap plugin installed
safe snap plugin configured correctly with osnap plugin as well
osnap plugin installed only
Closes: #
1. go to a space you can add plugins to
2. add the safesnap plugin but dont configure it correctly
3. see that we warn you of an issue cant proceed
4. configure safesnap correctly, see that you can proceed
5. add osnap plugin, see that you get a warning, but can still …
=> fix: unblock safesnap users from making transactions with osnap

src/views/DelegateView.vue
Closes: #4540 
Fix missing space on small screen, for the last block element
1. Go https://snapshot.org/#/delegate/ens.eth
2. On small screen, the last block (with the confirm button) should have a margin top
=> fix(ui): fix missing spacing on small screen

src/composables/useProfiles.ts, src/views/ProfileView.vue
- on the delegate page ([example](https://github.com/groninge01/snapshot.git)) the profile name is not shown
- clicking on the profile (address) takes you to [the profile page](https://snapshot.org/#/profile/0x641e10cd6132d3e3fa01bfd65d2e0afcf64b136a) where again the profile name is not shown
- if you go to [the profile page with the address in the 'original' casing](https://snapshot.org/#/profile/0x641e10Cd6132D3e3FA01bfd65d2e0afCf64b136A) then the profile name is shown
- lowercase the address from the route param on the profile page
- lowercase the (address) id gotten from the `Users` query (or lowercase the id in the backend?)
- delegate page
- profile page (with lowercase address in url)
1. See above
=> lowercase address

src/assets/css/main.scss, src/components/Tune/TuneButton.vue
As discussed on the design call we want to have the primary button color black and white for the default skin. Custom domains are unchanged and will work as before.
=> fix: button primary color to black and white

src/composables/useProfiles.ts
Continueing on from PR #4550 we're doing our first delegate vote and noticed the profile name doesn't show up on the proposal page.
The solution looks to be to also lowercase the (profile) address.
=> Lowercase profile address

src/components/SettingsVotingBlock.vue, src/components/Tune/TuneInputDuration.vue
No error messages for voting delay and period, which can confuse users if we merge this PR https://github.com/snapshot-labs/snapshot.js/pull/961
1. Go to your space settings -> voting tab -> enter invalid values into `delay` and `period`
2. No error before
3. After fix, you should see errors similar to other inputs
=> fix: Add error messages on input duration

src/plugins/oSnap/constants.ts, src/plugins/oSnap/utils/coins.ts, src/plugins/oSnap/utils/getters.ts, src/plugins/safeSnap/constants.ts, src/plugins/safeSnap/utils/coins.ts
We want to add core dao support in oSnap.  This adds core support in oSnap plugin and safesnap plugin.  Due to external dependencies we are only able to get partial support for core but basic transactions will work. We are shipping this with partial support for Core, as the Coredao team is aware of this. 
There are still couple of outstanding issues for adding Core support:
- Safe app links in both oSnap/safeSnap tx builder does not work as Core Safe app instance does not support safe externally
- Transaction builder is not able to automatically fetch contract ABI since Core chain explorer requires API key to fetch that.
- Transaction builder fails to load token/NFT balances for Core as Covalent service does not support Core network:
1. Add core treasury to safe snap enabled space
2. See …
=> feat: add core network support to osnap plugin

src/plugins/oSnap/Create.vue, src/plugins/oSnap/components/TransactionBuilder/TokensModalItem.vue, src/plugins/oSnap/components/TransactionBuilder/TransferFunds.vue, src/plugins/oSnap/utils/getters.ts
There was a bug in the transaction builder where the app would load all tokens you have balances for (your safe on a certain network), then when you switch safes, that list of tokens would not update. We also were not including the balance of the native token in the token chooser modal. This was because the balance pulled from gnosis, if that balance was for a native token it would be stripped out by the app, then later we just hardcoded in the native asset for the chain as an option, but without the balance info.
This PR rectifies some of the state management so that we reload token balances and token lists when we switch safes.
It also ensures we keep the safe's balance for native tokens so we can display this data to the user.
1. go to an osnap plugin enabled space
2. create a …
=> fix: osnap snapshot tx builder bug

src/components/ModalTreasury.vue, src/helpers/utils.ts, src/plugins/oSnap/Create.vue, src/plugins/oSnap/utils/getters.ts
When calling safe's API to fetch token balances for a particular safe, the checksum check would sometimes fail.
This PR ensures that:
- If a user attempts to add a treasury with a mixed-case or non-checksum address, we convert it first.
- All calls to gnosis api converts addresses to checksum, in case.
Closes: #
1. Go to settings > advanced > add treasury > enter mixed case or lowercase address 
2. See that the submitted safe address is correctly converted to checksum
=> fix: store safe addresses as checksum

src/helpers/constants.ts
Adds Mantle Safe host to known hosts to enable multi-signature wallets interact with snapshot as a safe app.
Mantle Safe URL: https://multisig.mantle.xyz
Closes: #4573 
1. Open Mantle Safe and either create or open safe wallet: https://multisig.mantle.xyz/welcome
2. Go to custom apps
3. Add snapshot URL (for mainnet: https://snapshot.org/, for testnet: https://testnet.snapshot.org/, local - http://localhost:8080)
4. Find a Mantle space and proposal and try voting. (For prepared test proposal see below).
- Open testnet (local) snapshot safe app in Mantle Safe;
- Search for "[Testing Snapshot Voting](https://testnet.snapshot.org/#/testingsafe.eth)" space (created for Mantle network).
- Navigate to the latest [proposal](https://testnet.snapshot.org/#/testingsafe.eth/proposal/0xb867235402eff21 …
=> feat: add mantle safe to known hosts

src/plugins/oSnap/utils/getters.ts
We have a proposal that cant be executed in osnap. This fixes the state machine logic to handle the case where we should be able to execute a proposal. 
currently it looks like this:
after fix:
1.  visit : /#/umadev.eth/proposal/0xb588a73b28666fb143e8c87473a9ca17abbd180875f5551d71de52354d0f7c0f
2. see that you can execute this proposal
=> fix(osnap): fix proposal execution step

src/views/PaymentNetwork.vue
The star background is not cut when the parent element have a border radius, making it spilling over the element
Closes: #
1. Go to  http://localhost:8080/#/payment/network
2. The star background on the first option should not overflow over the border radius
=> fix(ui): fix overflowing image due to border radius

src/components/SpaceProposalBoost.vue, src/components/SpaceProposalBoostItem.vue, src/composables/useBoost.ts, src/views/SpaceProposals.vue
1. With lottery sometimes rewards turn out to be higher because were not enough voters. So instead of just changing the reward amount in the boost description when rewards are final (like we discussed), I decided to show a message because I think it will be confusing for the user to see a different reward amount in the boost description than he saw previously. 
2. Sanitize boosts where proposal end doesn't match boost start time.
3. Sanitize boosts that don't have 2 week period
=> fix: Boost fixes

src/assets/css/tune.scss, src/components/Tune/TuneSelect.vue, src/views/SpaceBoost.vue
Until I find a good solution for Listbox lets use Select component.
Works the same as before, when bribe is disabled
=> fix: use select instead of listbox for boost eligibility dropdown 

src/components/SpaceProposalPage.vue, src/components/SpaceProposalPlugins.vue
1. These is a case when oSnap is enabled in the space settings which will cause an error on proposals that were previously created. This adds a check to make sure oSnap is also defined in the `proposal.plugins`
2. Fix conditions in `SpaceProposalPage`. We were checking for `proposal.plugins` on `SpaceProposalPlugins` and `SpaceProposalPluginsSidebar` which is always defined as `{}` so this check wasn't doing anything.
=> Fix oSnap plugin

src/components/SettingsLinkBlock.vue
Right now if you go to space settings, you will see 
and error 
With this fix, you should see the social accounts section
=> fix: Social accounts section is missing

src/composables/useUsername.ts
There is a case where `web3Account.value` could be `null` , considering this https://github.com/snapshot-labs/snapshot/blob/master/src/composables/useWeb3.ts#L81 so In such cases, it will return an error `Cannot read properties of null (reading 'toLowerCase')` which can result in following view
=> Fix: webAccount.value can possibly be a null

src/plugins/oSnap/constants.ts, src/plugins/safeSnap/constants.ts
With the deprecation of Goerli we need to add Sepolia testnet support for oSnap.
This adds Sepolia testnet support in oSnap plugin and safeSnap plugins.
1. Add Sepolia treasury to safe snap enabled space
2. See that you can create proposals with osnap and sepolia testnet transactions
=> feat: add sepolia testnet support to osnap plugin

src/components/ModalPostVote.vue, src/components/ModalStrategies.vue, src/components/ModalVote.vue, src/components/SettingsStrategiesBlock.vue, src/components/SpaceProposalInformation.vue, src/components/StrategiesListItem.vue, src/locales/default.json, src/plugins/hal/components/CustomBlock.vue, src/plugins/oSnap/Proposal.vue, src/plugins/poap/components/CustomBlock.vue, src/plugins/progress/components/CustomBlock.vue, src/plugins/projectGalaxy/components/CustomBlock.vue, src/plugins/safeSnap/components/Config.vue, src/plugins/safeSnap/components/SafeTransactions.vue, src/views/SpaceAbout.vue
For consistency I've refactored modal and block components on the proposal page to use tune components, to match the changes from the Boost PR.
| Before                | After                 |
|-----------------------|-----------------------|
|  <img width="492" alt="Screenshot 2024-03-19 at 4 54 25 in the afternoon" src="https://github.com/snapshot-labs/snapshot/assets/51686767/0a7e3992-dcfe-4065-a8f8-64bacd45f80b"> | <img width="472" alt="Screenshot 2024-03-19 at 4 54 18 in the afternoon" src="https://github.com/snapshot-labs/snapshot/assets/51686767/eb0b72d5-2545-4fd4-99a4-b9a81a8f14b3"> |
| <img width="662" alt="Screenshot 2024-03-19 at 4 53 05 in the afternoon" src="https://github.com/snapshot-labs/snapshot/assets/51686767/be654b30-5415-49f2-af9a-b9369f4d33e8"> | <img width="664" …
=> refactor: use tune components on proposal page

src/components/TheFlashNotification.vue
Context: https://discord.com/channels/955773041898573854/1221106380300357804/1221141225751576646
Right now we display two X icons on flash notification (which is confusing)
Now changed into exclamation circle icon 
1. Try to do any signature and reject sign in wallet
2. For example, Go to any proposal, try to vote and click reject in metamask model
=> fix: Replace X icon on flash notification with exclamation icon

src/composables/useBoost.ts, src/plugins/oSnap/Create.vue, src/plugins/oSnap/components/TransactionBuilder/TransferFunds.vue, src/plugins/oSnap/constants.ts, src/plugins/oSnap/utils/coins.ts, src/plugins/oSnap/utils/getters.ts
Optimism chain is not working with oSnap. This adds in OP data, such as token info and api endpoints, as well as fixes issues in rendering when certain data is not available. 
Closes: #
1. find an osnap enabled space with an optimism treasury ( #/umadev.eth/create )
2. create a new osnap proposal
3. select the optimism safe, add new transaction
4. see that it loads correctly
5. select contract interaction, use this address: 0xcDF27F107725988f2261Ce2256bDfCdE8B382B10
6. load abi
7. see that abi loads
=> fix: fix optimism chain in osnap

src/components/SetupDomain.vue, src/helpers/connectors.ts, src/helpers/ens.ts
Related to https://github.com/snapshot-labs/snapshot/issues/4614
- Change .env to 
```
VITE_ENV=demo
VITE_DEFAULT_NETWORK=11155111
```
- When you go to http://localhost:8080/#/setup?step=1 you should see ENS names from sepolia
- When you go to your space, you should be able to get controller from sepolia 
- You should be able to create new spaces using sepolia ENS
=> Add ENS support for sepolia

src/helpers/boost/index.ts
Add Shutter DAO space (shutterdao0x36.eth) to Boost beta testing whitelist as per their request.
=> Add Shutter DAO to Boost testers

src/components/SettingsVotingBlock.vue, src/composables/useFormSpaceSettings.ts, src/helpers/interfaces.ts, src/helpers/queries.ts, src/locales/default.json
Related to https://github.com/snapshot-labs/snapshot/issues/4600
Add a new field `quorumType` to space settings
- Default to `default`, or can be `optimistic`
- if value is `default` we store empty string on backend
Make sure to change quorum type to default or optimistic
=> feat: Add quorum type to space settings

src/components/SettingsTreasuriesBlock.vue, src/components/SetupDomain.vue
Related to https://github.com/snapshot-labs/snapshot-sequencer/pull/321
Before
After
=> fix: Hide very long ENS names

src/views/DelegateView.vue
Closes #4659 
Previously only delegation strategy works on delegation page, this PR will add `erc20-balance-of-delegation` and `delegation-with-cap` as these strategies are very similar to delegation strategy and should not create any problems
- Go to https://snapshot-2xwxdbhwj-snapshot.vercel.app/#/delegate/balancer.eth and you should see top delegates
=> fix: Add support for delegation related strategies on delegation page

src/components/ModalPostVote.vue, src/plugins/oSnap/utils/getters.ts, src/plugins/safeSnap/components/SafeTransactions.vue
Changes safe URL to new domain 
While reviewing https://github.com/snapshot-labs/snapshot/pull/4649 I noticed we are still using old domain and it is broken 
- Trust me bro 🤣 
Or 
- Vote with a safe and after voting a model will be open, you should see the link to the transactions queue
- Go to http://localhost:8080/#/shapeshiftdao.eth/create
- Login with an admin account using guest tool
- You should see new safe app link in oSnap transactions 
- ![image](https://github.com/snapshot-labs/snapshot/assets/15967809/a1c67518-dbaf-425a-bd60-21eaac673372)
=> fix: Change Safe URL

src/locales/default.json, src/plugins/domino/ProposalSidebar.vue, src/plugins/domino/components/CustomBlock.vue, src/plugins/domino/plugin.json
Domino is a workflow automation platform created for connecting Web2 and Web3.
We recently integrated Snapshot and created a few templates that could benefit any Snapshot space. 
The plugin creates a ProposalSidebar widget, showing 5 templates we think are useful. It also allows users to create custom workflows using the Snapshot trigger 
1. Create a test space
2. Enable the Domino plugin in advanced settings
3. In the proposal sidebar a new "Automations" widget will appear
=> Feat: Add Domino plugin and components

src/components/ModalVote.vue, src/components/SetupMessageHelp.vue, src/components/SpaceCreateWarnings.vue, src/components/SpaceProposalResults.vue, src/components/SpaceProposalVote.vue, src/components/SpaceProposalsNotice.vue, src/components/TheFooter.vue, src/components/TheModalNotification.vue, src/helpers/constants.ts, src/locales/default.json, src/views/SpaceDelegates.vue
Replacing support links with new help center link
- Go to places where we have support links
- for example
- on space creation:
- Footer:
- While voting:
=> fix: Replace support links with help center link

src/components/ProposalsItemFooter.vue, src/components/SettingsVotingBlock.vue, src/components/SpaceProposalResultsQuorum.vue, src/composables/useQuorum.ts, src/helpers/interfaces.ts
Related to https://github.com/snapshot-labs/snapshot/issues/4600
Now we call it "Quorum of rejection"
1. Go to https://snapshot-git-rename-to-quorum-of-rejection-snapshot.vercel.app/#/thanku.eth/settings
settings -> voting -> Change quorum type to "Quorum of rejection"
2. Create new proposal
3. Try to vote on second option and you will see quorum is updated
5. Check proposals page
=> Rename to 'Quorum of rejection'

src/components/SettingsTreasuriesBlockItemButton.vue, src/plugins/oSnap/Create.vue, src/plugins/oSnap/types.ts, src/plugins/oSnap/utils/getters.ts, src/plugins/safeSnap/constants.ts
When adding a safe for a network which does NOT have a subgraph defined in the config, uncaught exceptions would crash the proposal page. This PR ensures, when we fetch all osnap enabled safes, we catch these exceptions and show a meaningful message in the console. In the transaction builder we also filter out any of those safes from the dropdown.
1. Add a treasury on a network **not** on this list `(1, 5, 10, 100, 137, 42161, 43114, 1116, 8453, 11155111)`.
2. Create a new proposal, see that you can not select this safe in the dropdown.
=> fix: prevent unsupported treasuries from crashing proposal page

src/composables/useChangeNetwork.ts
ChainId is wrong while switching the network
- Make sure your metamask wallet network is sepolia
- Go to http://localhost:8080/#/thanku.eth/boost/0x9ef1c0ad8329186500866f5962c24f8d49a382857b3ebe49f9b4615193ab72ad
- Select Ethereum and some token to deposit
- Click on "Create"
- Before fix you will see error, now you should see that wallet is open to change the network
=> fix: ChainId is wrong while switching the network

src/components/SettingsTreasuriesBlockItemButton.vue
Small fix in logic to show/hide the "activate oSnap" button in `Settings => Advanced`.
Currently if a space doesn't have osnap plugin installed it will show "oSnap unavailable". We only want this to show only if the plugin IS installed but there is no subgraph defined for the network.
1. Go to `Space => Settings => Advanced => Treasury Section`
2. If oSnap plugin installed and the network is supported (we have config) we show a button with either `activate osnap` or `oSnap activated` OR if no config for this chain we show text "oSnap unavailable"
3. If oSnap plugin not installed, show nothing.
=> fix: only show activation button if plugin installed

src/helpers/connectors.ts
The chainId for Sepolia is `11155111` but it was `1115511` in the walletconnect connector config. Trying to connect to Snapshot with a Safe on Sepolia doesn't work.
Follow up on #4622 
1. Run the snapshot app
2. Press the connect wallet button and choose walletconnect
3. Copy the wc uri and open app.safe.global with a Safe on Sepolia
4. Paste the wc uri in the header
5. It should be possible to Approve the connection
=> fix: Use correct chainId for sepolia in walletconnect config

src/helpers/constants.ts
Summary
Adds Moonbeam Safe host to known hosts to enable multi-signature wallets interact with snapshot as a safe app.
Moonbeam Safe URL: https://multisig.moonbeam.network
Closes: https://github.com/snapshot-labs/snapshot/issues/4698
How to test
1. Open Moonbeam Safe and either create or open safe wallet: https://multisig.moonbeam.network
2. Go to custom apps
3. Add snapshot URL (for mainnet: https://snapshot.org/, for testnet: https://testnet.snapshot.org/, local - http://localhost:8080/)
4. Find a Moonbeam space and proposal and try voting.
=> feature: add moonbeam safe to known hosts

src/locales/default.json
Closes #4701 
- Go to your space settings => voting
| Before | After |
| ------  | ----- |
| <img width="676" alt="image" src="https://github.com/snapshot-labs/snapshot/assets/15967809/d247dfa6-f55c-43e7-b131-8a2ef8e8efad"> | <img width="668" alt="image" src="https://github.com/snapshot-labs/snapshot/assets/15967809/4b69d95b-ad74-42db-a2d5-af3341962c0f"> |
| <img width="458" alt="image" src="https://github.com/snapshot-labs/snapshot/assets/15967809/4e00be44-a778-4054-83b5-ee66a284ddf3"> | <img width="444" alt="image" src="https://github.com/snapshot-labs/snapshot/assets/15967809/e38aea01-350f-43db-a3c5-820d1db1998e">|
=> fix: Privacy label name for any option

src/components/ModalAccount.vue, src/helpers/connectors.ts
Right now, if Coinbase is injected, we display two Coinbase connectors, which is confusing.
1. Disable other wallet extensions except coinbase wallet 
2. Try to connect wallet on snapshot 
3. Now we should see only one coinbase
Or 
1. open snapshot in coinbase mobile wallet
2. now we should see only one coinbase instead of two
=> fix: Hide walletlink if coinbase is injected

src/composables/useWeb3.ts
While using coinbase wallet extension, if we switch the account in a new tab, the injected object is not updated, so whenever user clicks logout and connects again, we always get previous address instead of current one
With this fix, If user clicks on logout, we close the connection so user have to connect again - which will fix all the account switch issuse
1. Make sure you have two accounts in coinbase wallet
2. Try connecting coinbase wallet to snapshot
3. In a new tab try changing the account to different account
4. click on logout and connect again
Before the fix, you should see that we still show previous address as connected address
After the fix, you should see the new address as connected address
=> fix: Coinbase wallet issue while switching accounts in different tab

src/composables/useAliasAction.ts, src/helpers/queries.ts
Related to https://github.com/snapshot-labs/snapshot-sequencer/pull/353/files
- Only use aliases that were created within the last 30 days
1. Try following/unfollowing a space with an alias created 30 days ago
2. It should ask to create new alias in this case
=> fix: Add created_gt filter to aliases query

src/components/SpaceProposalBoost.vue, src/components/SpaceProposalBoostItem.vue, src/helpers/boost/types.ts, src/views/SpaceBoost.vue
Boost reward to winning choice 
- Add a new eligibility type for boost winning choice
- Change text to "Anyone who votes to winning choice" if eligibility type is `prediction` 
1. Create a new proposal and try to create a new boost with new eligibility type
2. vote and proposal and make sure your choice is winning 
3. Claim
=> feat: Boost reward to winning choice

src/main.ts
Closes: #
Disable the sentry plugin, as it's not currently used, and is triggering warning on AVG
1.
=> fix: disable sentry

src/components/TheFooter.vue
Footer link for network support should open in same tab
1. Go to footer in home page
2. click on network support
3. now it should open in same tab instead of new tab
=> fix: footer link for network support should open in same tab

src/views/ExploreView.vue, src/views/Network.vue
- Change the network page link on the networks page
- Remove horizontal scroll for the customers section (approved by `less`)
Details: https://discord.com/channels/955773041898573854/1031838169282392144/1248618727898091612
1. ![image](https://github.com/snapshot-labs/snapshot/assets/15967809/c8306863-a51a-4364-92fc-a39ac33a3c2f)
2. On click of this button, we should go to the network page instead
3. Under "Trusted by" we should not see the scroll anymore. instead we see all customers
4. <img width="370" alt="Untitled 2" src="https://github.com/snapshot-labs/snapshot/assets/15967809/e10ae5fb-bc9c-4960-b85d-1778ce1763c7">
=> fix: Change network page link and remove horizontal scroll for customers section

src/views/Network.vue
Adds new existing network section to network page
1. Go to http://localhost:8080/#/network
2. You should see the new section same as https://snapshotx.xyz/#/network
=> fix: Add existing network section to network page

src/views/ProfileView.vue
Profile page doesn't show any activity https://discord.com/channels/955773041898573854/1182427601046884352/1249731067963904050
- Problem: Profile page doesn't show any activity
- Profile page: Check if the address param an address or not
- if not, show an error
- if yes, send requests to hub only with checksummed address instead of lowercase
1. Go to http://localhost:8080/#/profile/0x24F15402C6Bb870554489b2fd2049A85d75B982f it should work normal and show activity
2. Go to http://localhost:8080/#/profile/0x24f15402c6bb870554489b2fd2049a85d75b982f should still work but send requests to hub with checksummed addresses
3. Go to http://localhost:8080/#/profile/ABCD should show a message
4. <img width="1644" alt="image" src="https://github.com/snapshot-labs/snapshot/assets/15967809/188811a5-f7b0- …
=> fix: Profile page - check for valid address and send requests only with checksummed addresses

src/plugins/oSnap/constants.ts, src/plugins/safeSnap/constants.ts
With the deprecation of hosted subgraph service oSnap/safeSnap plugins are migrated to Subgraph Studio.
1. Open a proposal with oSnap or safeSnap transactions
2. Verify that proposal status is correctly resolved.
- Goerli subgraphs are not migrated as due to chain deprecation it is not supported in Subgraph Studio. We should deprecate Goerli for oSnap/safeSnap altogether in a follow-up PR.
=> fix: migrate osnap to subgraph studio

src/plugins/gnosis/index.ts
Use upgraded subgraphs and remove deprecated networks
=> chore: Change subgraph URLs in gnosis plugin

src/components/SpaceProposalVote.vue
There is an issue when the URL contains selected choice `?choice=1` (used by discord bot),
- Try going to https://snapshot.org/#/thanku.eth/proposal/0x72d902d7c3cfc0c52dd2d890321cb5778e73429d544fe2d14a24d96280a02680?choice=1 and it should print an error in console
- With my change, we give preference to the selected choice instead of the user vote (which is null if the user doesn't vote yet)
1.  Go any proposal with `?choice=1`  for example https://snapshot-git-fix-selected-choice-snapshot.vercel.app/#/thanku.eth/proposal/0x72d902d7c3cfc0c52dd2d890321cb5778e73429d544fe2d14a24d96280a02680?choice=1
2. Connect your wallet
3. You should be able to vote with pre-selected choice
=> fix: Prefer selected choice over user vote

src/components/ModalVote.vue
- Issue: When the model is open automatically due to `?choice=1`, voting power is not loading on the modal
- If you go to https://snapshot.org/#/cowgrants.eth/proposal/0x9214658a7ee9e1dc42f0d9f9c64b8470603d85df9518b2c6b70e94d915aafd6c?choice=1
- voting power will keep loading
1. Go to a proposal with `?choice=1`
2. https://snapshot.org/#/cowgrants.eth/proposal/0x9214658a7ee9e1dc42f0d9f9c64b8470603d85df9518b2c6b70e94d915aafd6c?choice=1
3. Voting power should load
4. ![image](https://github.com/snapshot-labs/snapshot/assets/15967809/b874aff4-250f-4b64-9bb9-3dd8b8fe0f03)
=> fix: Load voting power immediately once vote modal is open

src/components/SpaceProposalVote.vue
This PR fix the issue where an error message is shown instead of the user's votes, on active proposals
1. Go to any active proposal you already voted on
2. It should show your votes instead of the error message
3. On proposals you have not voted on, it should show the full vote form
4. By appending `?choice=1` to the end of the url (on basic and single choice proposal), it should open the vote modal on page load, with the choice `1` as selected
=> fix: fix invalid selected choices computation

src/components/BaseMarkdown.vue
Some links are not working if it contains `_` 
this fix will escape `_` with `/_` 
1. Go to http://localhost:8080/#/gov.bloomstudio.eth/proposal/0x6f6e3458c0ee772569eca7cf03fa323e2f31870c2293898a083ca3ffbb73247f
2. Before the fix:
3. After the fix:
=> fix: Escape underscores in links

src/components/SpaceProposalHeader.vue
Proposal author doesn't load on the page load, but works fine if we go from proposals page
1. Go to https://snapshot.org/#/unidexapp.eth/proposal/0xc588b51bc4c4f59741b110c32be503a012ba9de5bb1148e361ffe0e5bed418bf 
2. Notice that proposal author doesn't load, but works fine if we go to proposal from proposals page
=> fix: Proposal author doesn't load

src/views/SpaceBoost.vue
On Boost, the number of winners should default to `1` 
1. Go to boost creation page
2. You should see the number of winners as `1`
3. Try switching between lottery and proportion
=> fix: Default value for number winners

src/views/SpaceBoost.vue
Fix from #4804 
- `numWinners` should be a string instead of a number
- Create a boost with `lottery` type
- In the pinned file, `"numWinners"` should be a string
=> fix: numWinners should be string instead of number

src/helpers/boost/subgraph.ts
Related to https://github.com/snapshot-labs/pitches/issues/84
- Use published subgraphs
- https://thegraph.com/explorer/subgraphs/A6EEuSAB7mFrWvLBnL1HZXwfiGfqFYnFJjc14REtMNkd?view=Query&chain=arbitrum-one
- https://thegraph.com/explorer/subgraphs/6T64qrPe7S46zhArSoBF8CAmc5cG3PyKa92Nt4Jhymcy?view=Query&chain=arbitrum-one
- https://thegraph.com/explorer/subgraphs/CkNpf5gY7XPCinJWP1nh8K7u6faXwDjchGGV4P9rgJ7?view=Query&chain=arbitrum-one
- https://thegraph.com/explorer/subgraphs/52uVpyUHkkMFieRk1khbdshUw26CNHWAEuqLojZzcyjd?view=Query&chain=arbitrum-one
1. Go to proposals with boosts (for ex: https://snapshot-git-fix-boost-subgraph-urls-snapshot.vercel.app/#/thanku.eth/proposal/0x72d902d7c3cfc0c52dd2d890321cb5778e73429d544fe2d14a24d96280a02680)
2. You should see boosts and rewards if you are …
=> fix: Use published subgraphs instead of test URLs

src/locales/ar-SA.json, src/locales/de-DE.json, src/locales/default.json, src/locales/es-ES.json, src/locales/fil-PH.json, src/locales/fr-FR.json, src/locales/id-ID.json, src/locales/it-IT.json, src/locales/ja-JP.json, src/locales/ko-KR.json, src/locales/pt-PT.json, src/locales/ro-RO.json, src/locales/ru-RU.json, src/locales/tr-TR.json, src/locales/zh-CN.json
Same as https://github.com/snapshot-labs/sx-monorepo/commit/66e98942a0fbebdb2a63e15b884361d2124fd0e0
=> fix: Update shutter URL

src/components/SpaceSidebarNavigation.vue
Full context: https://discord.com/channels/955773041898573854/1280744653183782963/1285552934804783144
- Ignores deleegation dashboard for these spaces
`'ens.eth', 'gitcoindao.eth', 'uniswapgovernance.eth'`
- Go to http://localhost:8080/#/gitcoindao.eth or http://localhost:8080/#/ens.eth
- Click on delegates
- Should open snapshot delegation instead of delegation dashboard
=> fix: Ignore delegation dashboard

src/components/SpaceDelegateEdit.vue, src/composables/useStatement.ts
Saving a new delegate statement is not doing anything, clicking on the "Save changes" button in the edit delegate statement form is not doing anything (no error shown)
This PR fix this issuem by setting the hidden field correctly
1. Go to a http://localhost:8080/#/cowtesting.eth/delegate/YOUR-ADDRESS or any other space with delegation dashboard where you don't have a statement yet
2. Edit and save the statement
3. It should save the statement
=> fix: fix invalid status when saving delegate statement

src/components/BaseBlock.vue, src/components/NavbarAccount.vue, src/components/ProfileAddressCopy.vue, src/views/SpaceDelegate.vue
This PR fixes a few UI issues where long text would overflow their container
- Limit username max length on topnav account to prevent this
- Do not shrink copyAddress button to prevent multi line button
- Force words break on BaseBlock to prevent overflow content
- Truncate username in SpaceDelegate top prevent overflow
=> fix(ui): fix overflowing text

src/App.vue
Closes: https://github.com/snapshot-labs/workflow/issues/210
Displays a banner on top of explore page and timeline page
Desktop:
Mobile:
1. go to explore page / timeline page
2. you should see new banner 
3. which should not show up once it is closed
=> feat: Show v2 banner

src/components/SetupStrategyBasic.vue
Context https://discord.com/channels/955773041898573854/1030773050217615440/1289392373037662208
Form will  now ask for symbol and decimals if covalent fail
1. Go to space creation, strategies page, select "Token weighted voting"
2. Select any network, Select any standard
3. Enter an invalid token (for example your EOA address)
4. It should ask for  symbol and decimals if covalent fail, instead of showing the error
5. You should be able to continue with space setup now
Before:
Now:
=> fix: Ask for symbol and decimals if covalent fail

src/components/SpaceDelegatesCard.vue, src/views/SpaceDelegates.vue
This PR loads and shows the statement for each delegation card, in the delegation dashboard.
Also proceeded to some little refactoring to truncate username when needed
1. Go to http://localhost:8080/#/test.wa0x6e.eth/delegates
2. Each delegation card now shows the statement, the username when available instead of just the address
=> feat: load statement in delegation dashboard

src/views/SpaceDelegates.vue
Trying to fix issue pointed out in https://jam.dev/c/cb4b5003-3dd9-4156-9ccb-dc4a5ac2fc36
When typing letters quickly in the search box, some requests are shown as "no results" wrongly.
This is somewhat hard to reproduce, this PR fix this by making the search `sync`, so any slow requests will not override latest results.
1. Go to http://localhost:8080/#/test.wa0x6e.eth/delegates?search=fabien.eth
2. It should load the card for the searched ENS name
3. Try typing something else in the searchbox quickly
4. It should load the results for the searched name
=> fix: fix search request not being resolved in order

src/components/SpaceDelegatesCard.vue, src/composables/useDelegates.ts, src/helpers/queries.ts, src/views/SpaceDelegate.vue
This PR load the votes and proposals count stats for each delegators, in the delegation dashboard (from the space leaderboard).
Until now, those stats were always showing `0`
1. Go to http://localhost:8080/#/test.wa0x6e.eth/delegates
2. It should show proper votes and proposals count for each users
3. Click on a card to show the delegator page
4. It should show the same stats in the sidebar
=> feat: load delegate stats

src/components/AvatarUser.vue
This PR fix an issue where the `UserAvatar` component was case sensitive, this considering 2 exact same addres, but with different case as different.
This PR will always checksummed the address
1. Go to http://localhost:8080/#/cowtesting.eth/delegates
2. Console inspect a random delegate with avatar
3. This avatar should have a timestamp params, and address is checksummed
4. Click on the card to go to delegate statement
5. The avatar in the sidebar should load immediately (since loaded from cache)
6. This avatar should have same same exact url as before (checksummed, and same timestamp params)
=> fix: fix stamp avatar case sensitiveness

src/composables/useDelegates.ts
This PR fix an issue when delegating using the delegation dashboard, when the address is not checksummed.
Issue happens when the address is resolved from ENS, since our ENSNameResolver is always returning a lowercase address, while the delegation form is accepting only checksummed address
1. Go to http://localhost:8080/#/cowtesting.eth/delegates?search=middleway.eth
2. It should show the delegation card for the address `0xA11DA8B2D9A7883eb636d7de426025e5fD9fda1A`
3. Clicking on the delegate button should open the delegate modal, with the address pre-populated in the form, and is a valid checksummed address
=> fix: fix wrong address case when resolved from ENS name

.github/workflows/test.yaml
This PR fix the failing test workflow, which now required `on` to be defined explicitly
- On this PR, all github actions are passing
=> ci: fix missing `on` property in test workflow

src/views/ExploreView.vue
- `network` route now redirects to v2 network page
- Go to https://snapshot.org/#/?filter=networks it throws in console and Add network button will be hidden
- In dev mode, it will not load the entire page
- After fix you should see the page and button
=> fix: Networks page doesn't work in dev mode

src/helpers/constants.ts, src/main.ts
Allow `*.blockscout.com` to show snapshot in iframes
Context https://discord.com/channels/955773041898573854/1125390177888645231/1290249564623736885
1. Go to https://eth.blockscout.com/apps/zerion, or https://optimism.blockscout.com/apps/zerion open console and edit HTML, replace with 
```HTML
<body>
<iframe src="http://localhost:8080/#/"></iframe>
</body>
```
2. Previously it should not allow
3. Now it should allow on all subdomains
4. It should allow snapshot on any other domains
=> feat: Domains list to allow iframe on all subdomains

src/helpers/connectors.ts
Same fix as https://github.com/snapshot-labs/sx-monorepo/pull/745
- moving all methods into optional methods
1. Go to http://localhost:8081/#/delegate/apecoin.eth
2. Connect to your safe with walletconnect (with new changes make sure to disconnect if you are already connected)
3. Delegete or remove delegate
4. Before fix. it will show error: "unknown account"
5. After fix: it will open transaction modal on Safe
=> fix: walletconnect options: move methods to optionalMethods

src/components/SpaceCreateVoting.vue, src/composables/useClient.ts
- Fix the proposal creation, which is broken because of https://github.com/snapshot-labs/snapshot.js/compare/v0.12.19...v0.12.20
1. Create a proposal on any space
2. Before it was throwing an error
=> fix: send empty labels with proposals

src/components/SettingsDelegationBlock.vue, src/composables/useFormSpaceSettings.ts, src/helpers/interfaces.ts, src/helpers/queries.ts
Closes: https://github.com/snapshot-labs/snapshot/issues/4912
This PR fixes the broken delegation portal, due to TuneForm not supporting having other thing than a choice list in `anyOf`, and missing `delegationNetwork` selector, not supported by TuneForm
1. Go to your space settings > Delegation 
2. The form should show properly, with a network selector 
3. It should save without error
=> fix: fix broken space delegationPortal settings

src/composables/useClient.ts, src/composables/useFormSpaceProposal.ts, src/composables/useFormSpaceSettings.ts, src/helpers/queries.ts, src/views/SpaceCreate.vue
Related to https://github.com/snapshot-labs/workflow/issues/143
- Keep existing labels on space settings update
- Keep existing labels on proposal update
1. Go to any space with labels (or add labels on v2)
2. Edit space settings, should keep the labels space
3. Create a proposal on v2 with labels
4. Edit proposal on v1, should keep the labels on proposal
=> fix: Keep existing labels on spaces and proposals

src/views/DelegateView.vue
Delegation is broken if space is using with-delegation strategies, Because:
1. with-delegation strategies are not whitelisted 
2. these strategies return checksummed addresses from score-api
1. Go to https://snapshot.org/#/delegate/moxie.eth
2. You should see top delegates
=> fix: Whitelist with-delegation strategies and use checksum addresses

src/helpers/interfaces.ts, src/views/PlaygroundView.vue
This PR adds the `space` params to the strategy playground.
Currently, we pass a hardcoded empty string as space when testing strategies, but some strategies like "split-delegation" have specific voting power for each space.
This PR adds a new "space" input to the playground, defaulting to empty string.
1. Go to http://localhost:8081/#/playground/split-delegation?query=eyJwYXJhbXMiOnsiYmFja2VuZFVybCI6Imh0dHBzOi8vZGVsZWdhdGUtYXBpLmdub3Npc2d1aWxkLm9yZyIsInN0cmF0ZWdpZXMiOlt7Im5hbWUiOiJlcmMyMC1iYWxhbmNlLW9mIiwicGFyYW1zIjp7InN5bWJvbCI6InZDT1cgKG1haW5uZXQpIiwiYWRkcmVzcyI6IjB4ZDA1N2I2M2Y1ZTY5Y2YxYjkyOWIzNTZiNTc5Y2JhMDhkNzY4ODA0OCIsImRlY2ltYWxzIjoxOH0sIm5ldHdvcmsiOiIxIn0seyJuYW1lIjoiZXJjMjAtYmFsYW5jZS1vZiIsInBhcmFtcyI6eyJzeW1ib2wiOiJ2Q09XIChHQykiLCJhZGRyZXNzIjoiMHhjMjBDOUMxM0U4NTNmYzY0ZDA1NGI3M2ZG …
=> feat: add `space` param to strategy playground

src/components/SpaceDelegatesCard.vue, src/components/SpaceDelegatesSplitDelegationModal.vue
This PR an issue where the statement is overflowing outside the delegation card
Before fix
After fix
1. Go to http://localhost:8081/#/paraswap-dao.eth/delegates
2. The card about `jameskbh.eth` should not overflow anymore
=> fix: fix overflowing statement

src/components/SetupExtras.vue, src/views/SpaceSettings.vue
Toward https://github.com/snapshot-labs/workflow/issues/362
This PR will disable the custom domain and skin section in the space settings, since it's not relevant anymore:
- the docs are outdated
- custom domain does not work on v1
- skin does not work on v1
1. Go to a space settings, then advanced
2. The section about custom domain and skin is gone
=> fix: disable irrelevant custom domain and skin section

src/components/SettingsStrategiesBlock.vue, src/helpers/constants.ts
Issue:
Fix:
Snapshot.js doesn't contain these limits anymore
1. Go to http://localhost:8080/#/moonwell-governance.eth you should see limit of 10 on strategies
2. Go to http://localhost:8080/#/mutantcatsvote.eth/settings you should see limit of 8 on strategies
=> fix: hardcode strategies limits

src/helpers/constants.ts, src/views/SpaceCreate.vue
Unable to create proposals because snapshot.js doesn't contain these limits
- http://localhost:8080/#/moonwell-governance.eth/create Body limit should be 40k
- http://localhost:8080/#/friendswithbenefits.eth/create Body limit should be 10k
=> fix: hardcode proposal body limits

src/composables/useClient.ts, src/views/SpaceCreate.vue
We don't have privacy selector on v1, so we send space's privacy and empty string if it is `any`
Closes https://github.com/snapshot-labs/workflow/issues/453
1. Go to space with privacy `shutter` 
2. Create a proposal
3. Proposal payload should contain `privacy: 'shutter'`
=> fix: use space privacy on proposal

src/views/StrategyView.vue
The Strategies link in https://v1.snapshot.box/#/strategy/sonic-staked-balance is not working, this page is still being shared to others to refer to the strategy
=> chore: update strategies link

tailwind.config.js
It stopped working with newer versions of node js
- changed module.exports to export default in tailwind.config.js
1. run `yarn dev`
2. open localhost:8080
3. before it fail with error `ReferenceError: module is not defined`
=> fix: switch to ES module export in tailwind config
